// ── Phone Comparison Database for Seniors ────────────────────────────────────

export interface Phone {
  slug: string
  name: string
  brand: 'Apple' | 'Samsung' | 'Google' | 'Motorola' | 'Lively' | 'Consumer Cellular' | 'Nothing'
  year: 2025 | 2026
  price: string
  priceNum: number
  thumbnail: string
  screenSize: string
  weight: string
  battery: string
  os: 'iOS' | 'Android'
  seniorScore: number
  easeOfUse: number
  screenReadability: number
  hearingAidRating: string
  emergencySOS: boolean
  fallDetection: boolean
  voiceAssistant: string
  waterResistant: boolean
  storage: string
  camera: string
  bestFor: string[]
  pros: string[]
  cons: string[]
  summary: string
}

export interface UseCase {
  slug: string
  label: string
  description: string
}

export const USE_CASES: UseCase[] = [
  { slug: 'bad-eyesight', label: 'Bad Eyesight', description: 'Phones with large, bright screens and excellent display visibility for seniors with vision challenges.' },
  { slug: 'hearing-aids', label: 'Hearing Aids', description: 'Phones rated highly for hearing aid compatibility so you never miss a call or notification.' },
  { slug: 'simplicity', label: 'Simplicity', description: 'The easiest phones to learn and use, perfect for seniors who want straightforward technology.' },
  { slug: 'photography', label: 'Photography', description: 'Great cameras for capturing grandkids, travel, and everyday moments without complexity.' },
  { slug: 'budget', label: 'Budget-Friendly', description: 'Affordable phones that still deliver the features seniors need most, without breaking the bank.' },
  { slug: 'big-screen', label: 'Big Screen', description: 'Phones with the largest screens for comfortable reading, video calls, and browsing.' },
  { slug: 'lightweight', label: 'Lightweight', description: 'Light, easy-to-hold phones for seniors who want comfort during long conversations or browsing.' },
  { slug: 'long-battery', label: 'Long Battery', description: 'Phones that last all day (or more) on a single charge so you never worry about running out.' },
  { slug: 'video-calls', label: 'Video Calls', description: 'The best phones for FaceTime, Zoom, and video chatting with family and friends.' },
  { slug: 'first-smartphone', label: 'First Smartphone', description: 'The ideal starter phones for seniors upgrading from a flip phone or getting their first smartphone.' },
]

const PHONES: Phone[] = [
  {
    slug: 'iphone-16',
    name: 'Apple iPhone 16',
    brand: 'Apple',
    year: 2025,
    price: '$799',
    priceNum: 799,
    thumbnail: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=400&fit=crop',
    screenSize: '6.1 inches',
    weight: '170g',
    battery: 'All-day (22 hours)',
    os: 'iOS',
    seniorScore: 9,
    easeOfUse: 9,
    screenReadability: 8,
    hearingAidRating: 'M3/T4',
    emergencySOS: true,
    fallDetection: true,
    voiceAssistant: 'Siri',
    waterResistant: true,
    storage: '128GB',
    camera: '48MP dual camera',
    bestFor: ['simplicity', 'video-calls', 'photography'],
    pros: [
      'Extremely intuitive interface that seniors learn quickly',
      'Excellent FaceTime video calling quality',
      'Crash and fall detection built in',
      'Long software support (5+ years of updates)',
      'Massive app ecosystem with senior-friendly apps',
    ],
    cons: [
      'Premium price tag',
      'Screen may feel small for some seniors',
      'No headphone jack — needs adapter or Bluetooth',
      'Charging cable different from most Android phones',
    ],
    summary: 'The iPhone 16 offers the best balance of ease-of-use and features for most seniors. Its intuitive interface, reliable fall detection, and excellent FaceTime make it a top pick for staying connected with family.',
  },
  {
    slug: 'iphone-16-plus',
    name: 'Apple iPhone 16 Plus',
    brand: 'Apple',
    year: 2025,
    price: '$899',
    priceNum: 899,
    thumbnail: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=400&fit=crop',
    screenSize: '6.7 inches',
    weight: '199g',
    battery: 'All-day+ (27 hours)',
    os: 'iOS',
    seniorScore: 9,
    easeOfUse: 9,
    screenReadability: 10,
    hearingAidRating: 'M3/T4',
    emergencySOS: true,
    fallDetection: true,
    voiceAssistant: 'Siri',
    waterResistant: true,
    storage: '128GB',
    camera: '48MP dual camera',
    bestFor: ['bad-eyesight', 'big-screen', 'video-calls', 'long-battery'],
    pros: [
      'Large 6.7-inch screen makes everything easier to read',
      'Longest battery life in the iPhone lineup',
      'Same intuitive iOS experience as smaller iPhone',
      'Fall detection and Emergency SOS via satellite',
      'Excellent speakers for hearing calls clearly',
    ],
    cons: [
      'Heavier and harder to use one-handed',
      'Expensive at $899',
      'May not fit in smaller pockets or purses',
      'Screen size can feel overwhelming at first',
    ],
    summary: 'The iPhone 16 Plus is ideal for seniors who struggle with small screens. Its 6.7-inch display and all-day battery make reading, video calls, and browsing comfortable without eye strain.',
  },
  {
    slug: 'iphone-se-4th-gen',
    name: 'Apple iPhone SE (4th Gen)',
    brand: 'Apple',
    year: 2025,
    price: '$429',
    priceNum: 429,
    thumbnail: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop',
    screenSize: '6.1 inches',
    weight: '167g',
    battery: 'All-day',
    os: 'iOS',
    seniorScore: 9,
    easeOfUse: 9,
    screenReadability: 8,
    hearingAidRating: 'M3/T4',
    emergencySOS: true,
    fallDetection: true,
    voiceAssistant: 'Siri',
    waterResistant: true,
    storage: '128GB',
    camera: '48MP single camera',
    bestFor: ['budget', 'simplicity', 'first-smartphone', 'lightweight'],
    pros: [
      'Most affordable new iPhone available',
      'Same easy iOS experience as premium iPhones',
      'Lightweight and comfortable to hold',
      'Fall detection and Emergency SOS included',
      'Face ID for simple, secure unlocking',
    ],
    cons: [
      'Single camera (no ultrawide or zoom)',
      'Smaller battery than Plus models',
      'No always-on display',
      'Fewer color options',
    ],
    summary: 'The iPhone SE 4th Gen is the best value iPhone for seniors who want Apple simplicity without the premium price. It has every safety feature that matters at nearly half the cost of an iPhone 16.',
  },
  {
    slug: 'samsung-galaxy-s25',
    name: 'Samsung Galaxy S25',
    brand: 'Samsung',
    year: 2025,
    price: '$799',
    priceNum: 799,
    thumbnail: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&h=400&fit=crop',
    screenSize: '6.2 inches',
    weight: '162g',
    battery: 'All-day',
    os: 'Android',
    seniorScore: 8,
    easeOfUse: 7,
    screenReadability: 8,
    hearingAidRating: 'M3/T3',
    emergencySOS: true,
    fallDetection: false,
    voiceAssistant: 'Google Assistant + Galaxy AI',
    waterResistant: true,
    storage: '128GB',
    camera: '50MP triple camera',
    bestFor: ['photography', 'lightweight'],
    pros: [
      'Lightweight and comfortable at just 162g',
      'Galaxy AI helps with translations and text',
      'Excellent 50MP triple camera system',
      'Easy Mode simplifies the home screen',
      'Seven years of software updates promised',
    ],
    cons: [
      'Android has a steeper learning curve than iOS',
      'No built-in fall detection',
      'Samsung bloatware can be confusing',
      'Bixby voice assistant is less reliable than Siri or Google',
    ],
    summary: 'The Galaxy S25 is a lightweight powerhouse with excellent cameras and Samsung Easy Mode for simpler navigation. Best for seniors who prefer Android or want AI-powered features.',
  },
  {
    slug: 'samsung-galaxy-s25-ultra',
    name: 'Samsung Galaxy S25 Ultra',
    brand: 'Samsung',
    year: 2025,
    price: '$1,299',
    priceNum: 1299,
    thumbnail: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&h=400&fit=crop',
    screenSize: '6.9 inches',
    weight: '218g',
    battery: 'All-day+ (30 hours)',
    os: 'Android',
    seniorScore: 7,
    easeOfUse: 6,
    screenReadability: 10,
    hearingAidRating: 'M3/T3',
    emergencySOS: true,
    fallDetection: false,
    voiceAssistant: 'Google Assistant + Galaxy AI',
    waterResistant: true,
    storage: '256GB',
    camera: '200MP quad camera with 100x zoom',
    bestFor: ['bad-eyesight', 'big-screen', 'photography', 'long-battery'],
    pros: [
      'Massive 6.9-inch screen — the biggest available',
      'Best-in-class camera with 100x zoom',
      'Built-in S Pen stylus for handwriting notes',
      'Incredible battery lasts well beyond a full day',
      'Galaxy AI features for translation and assistance',
    ],
    cons: [
      'Very expensive at $1,299',
      'Heavy at 218g — can cause hand fatigue',
      'Complex features can overwhelm new users',
      'S Pen adds features most seniors may never use',
    ],
    summary: 'The Galaxy S25 Ultra has the biggest, brightest screen and best camera of any phone, but its complexity and weight make it better suited to tech-savvy seniors who want the absolute best.',
  },
  {
    slug: 'samsung-galaxy-a16',
    name: 'Samsung Galaxy A16',
    brand: 'Samsung',
    year: 2025,
    price: '$199',
    priceNum: 199,
    thumbnail: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop',
    screenSize: '6.5 inches',
    weight: '192g',
    battery: 'Two-day (5,000mAh)',
    os: 'Android',
    seniorScore: 7,
    easeOfUse: 7,
    screenReadability: 8,
    hearingAidRating: 'Compatible',
    emergencySOS: true,
    fallDetection: false,
    voiceAssistant: 'Google Assistant',
    waterResistant: true,
    storage: '128GB',
    camera: '50MP triple camera',
    bestFor: ['budget', 'long-battery', 'big-screen'],
    pros: [
      'Extremely affordable at just $199',
      'Massive battery lasts up to two days',
      'Large 6.5-inch screen for easy reading',
      'Water resistant — survives accidental spills',
      'Six years of security updates',
    ],
    cons: [
      'Slower processor than premium phones',
      'Camera quality drops in low light',
      'No wireless charging',
      'Plastic build feels less premium',
    ],
    summary: 'The Galaxy A16 offers remarkable value with a big screen, two-day battery, and water resistance for under $200. An excellent budget choice for seniors who need reliability without premium features.',
  },
  {
    slug: 'samsung-galaxy-a36',
    name: 'Samsung Galaxy A36',
    brand: 'Samsung',
    year: 2025,
    price: '$299',
    priceNum: 299,
    thumbnail: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop',
    screenSize: '6.6 inches',
    weight: '186g',
    battery: 'Two-day (5,000mAh)',
    os: 'Android',
    seniorScore: 8,
    easeOfUse: 7,
    screenReadability: 9,
    hearingAidRating: 'Compatible',
    emergencySOS: true,
    fallDetection: false,
    voiceAssistant: 'Google Assistant',
    waterResistant: true,
    storage: '128GB',
    camera: '50MP triple camera with OIS',
    bestFor: ['budget', 'long-battery', 'big-screen', 'first-smartphone'],
    pros: [
      'Great value at $299 with premium-feeling build',
      'Smooth 120Hz display makes scrolling buttery',
      'Two-day battery life on a single charge',
      'Large bright screen ideal for reading',
      'Samsung Easy Mode available for simplified interface',
    ],
    cons: [
      'No wireless charging',
      'Camera not as good as flagship phones',
      'No fall detection feature',
      'Can feel slightly heavy for smaller hands',
    ],
    summary: 'The Galaxy A36 hits the sweet spot between price and quality for budget-conscious seniors. Its large smooth display, two-day battery, and Samsung Easy Mode make it a reliable daily companion.',
  },
  {
    slug: 'google-pixel-9',
    name: 'Google Pixel 9',
    brand: 'Google',
    year: 2025,
    price: '$799',
    priceNum: 799,
    thumbnail: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=400&fit=crop',
    screenSize: '6.3 inches',
    weight: '198g',
    battery: 'All-day (24+ hours)',
    os: 'Android',
    seniorScore: 8,
    easeOfUse: 8,
    screenReadability: 9,
    hearingAidRating: 'M3/T3',
    emergencySOS: true,
    fallDetection: true,
    voiceAssistant: 'Google Assistant',
    waterResistant: true,
    storage: '128GB',
    camera: '50MP dual camera with AI editing',
    bestFor: ['photography', 'simplicity', 'video-calls'],
    pros: [
      'Cleanest, simplest Android experience available',
      'Outstanding camera with AI-powered photo editing',
      'Built-in fall detection and car crash detection',
      'Google Assistant is the best voice assistant on Android',
      'Seven years of guaranteed updates',
    ],
    cons: [
      'Not as intuitive as iPhone for complete beginners',
      'No Samsung Easy Mode equivalent',
      'Can get warm during heavy camera use',
      'Limited availability at some carriers',
    ],
    summary: 'The Pixel 9 delivers the cleanest Android experience with an incredible camera and built-in fall detection. Ideal for seniors who want great photos and straightforward Google software.',
  },
  {
    slug: 'google-pixel-9-pro',
    name: 'Google Pixel 9 Pro',
    brand: 'Google',
    year: 2025,
    price: '$999',
    priceNum: 999,
    thumbnail: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=400&fit=crop',
    screenSize: '6.3 inches',
    weight: '199g',
    battery: 'All-day (24+ hours)',
    os: 'Android',
    seniorScore: 8,
    easeOfUse: 8,
    screenReadability: 9,
    hearingAidRating: 'M3/T3',
    emergencySOS: true,
    fallDetection: true,
    voiceAssistant: 'Google Assistant',
    waterResistant: true,
    storage: '128GB',
    camera: '50MP triple camera with 30x zoom',
    bestFor: ['photography', 'video-calls'],
    pros: [
      'Best camera on any Android phone for 2025',
      'Triple camera with excellent 30x zoom',
      'Fall detection and Emergency SOS included',
      'Clean, bloat-free Android interface',
      'Gemini AI assistant for helpful suggestions',
    ],
    cons: [
      'Expensive at $999',
      'Camera features can feel overwhelming',
      'Same screen size as regular Pixel 9',
      'Pro features may be overkill for basic use',
    ],
    summary: 'The Pixel 9 Pro is the photographer\'s dream phone with a triple camera and 30x zoom. Best for seniors who love capturing memories and want the cleanest Android experience.',
  },
  {
    slug: 'google-pixel-8a',
    name: 'Google Pixel 8a',
    brand: 'Google',
    year: 2025,
    price: '$499',
    priceNum: 499,
    thumbnail: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=400&fit=crop',
    screenSize: '6.1 inches',
    weight: '188g',
    battery: 'All-day (24+ hours)',
    os: 'Android',
    seniorScore: 8,
    easeOfUse: 8,
    screenReadability: 8,
    hearingAidRating: 'M3/T3',
    emergencySOS: true,
    fallDetection: true,
    voiceAssistant: 'Google Assistant',
    waterResistant: true,
    storage: '128GB',
    camera: '64MP dual camera',
    bestFor: ['budget', 'simplicity', 'first-smartphone'],
    pros: [
      'Excellent value at $499 with flagship-level camera',
      'Clean Android with no bloatware',
      'Fall detection and crash detection built in',
      'Seven years of software updates',
      'Google Assistant works exceptionally well',
    ],
    cons: [
      'Screen slightly smaller than competitors at this price',
      'Plastic back feels less premium',
      'No telephoto zoom lens',
      'Slower charging than flagship Pixels',
    ],
    summary: 'The Pixel 8a is the best mid-range Android phone for seniors, combining Google\'s clean software with fall detection and an excellent camera at a reasonable price.',
  },
  {
    slug: 'motorola-moto-g-power-2025',
    name: 'Motorola Moto G Power (2025)',
    brand: 'Motorola',
    year: 2025,
    price: '$299',
    priceNum: 299,
    thumbnail: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400&h=400&fit=crop',
    screenSize: '6.7 inches',
    weight: '190g',
    battery: 'Three-day (6,000mAh)',
    os: 'Android',
    seniorScore: 7,
    easeOfUse: 7,
    screenReadability: 9,
    hearingAidRating: 'Compatible',
    emergencySOS: true,
    fallDetection: false,
    voiceAssistant: 'Google Assistant',
    waterResistant: true,
    storage: '128GB',
    camera: '50MP dual camera',
    bestFor: ['budget', 'long-battery', 'big-screen'],
    pros: [
      'Incredible three-day battery life',
      'Large 6.7-inch screen for easy reading',
      'Very affordable at $299',
      'Water-repellent design handles splashes',
      'Clean, near-stock Android experience',
    ],
    cons: [
      'Camera quality is average in low light',
      'No fall detection feature',
      'Slower software updates than Samsung or Google',
      'Build quality feels budget-oriented',
    ],
    summary: 'The Moto G Power is the battery champion with an astounding three-day battery life. Perfect for seniors who hate charging their phone and want a big, readable screen on a budget.',
  },
  {
    slug: 'motorola-edge-2025',
    name: 'Motorola Edge (2025)',
    brand: 'Motorola',
    year: 2025,
    price: '$549',
    priceNum: 549,
    thumbnail: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400&h=400&fit=crop',
    screenSize: '6.6 inches',
    weight: '174g',
    battery: 'All-day+ (5,000mAh)',
    os: 'Android',
    seniorScore: 7,
    easeOfUse: 7,
    screenReadability: 9,
    hearingAidRating: 'Compatible',
    emergencySOS: true,
    fallDetection: false,
    voiceAssistant: 'Google Assistant',
    waterResistant: true,
    storage: '256GB',
    camera: '50MP triple camera with OIS',
    bestFor: ['photography', 'big-screen', 'lightweight'],
    pros: [
      'Beautiful curved OLED display',
      'Lightweight at 174g despite large screen',
      'Triple camera with optical stabilisation',
      'Generous 256GB storage included',
      'Wireless charging support',
    ],
    cons: [
      'Motorola software updates are slower',
      'No fall detection',
      'Curved screen can cause accidental touches',
      'Less well-known brand support network',
    ],
    summary: 'The Motorola Edge offers a beautiful large display and triple camera at a mid-range price. A solid choice for seniors who want a premium-feeling phone without the flagship cost.',
  },
  {
    slug: 'lively-jitterbug-smart4',
    name: 'Lively Jitterbug Smart4',
    brand: 'Lively',
    year: 2025,
    price: '$149',
    priceNum: 149,
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=400&fit=crop',
    screenSize: '6.5 inches',
    weight: '195g',
    battery: 'All-day',
    os: 'Android',
    seniorScore: 10,
    easeOfUse: 10,
    screenReadability: 10,
    hearingAidRating: 'M4/T4',
    emergencySOS: true,
    fallDetection: true,
    voiceAssistant: 'Google Assistant',
    waterResistant: false,
    storage: '32GB',
    camera: '13MP single camera',
    bestFor: ['simplicity', 'bad-eyesight', 'hearing-aids', 'first-smartphone', 'budget'],
    pros: [
      'Designed specifically for seniors — the easiest phone to use',
      'Huge text and simple list-based menu',
      'Urgent Response button connects to 24/7 agents',
      'Top hearing aid compatibility rating (M4/T4)',
      'Fall detection with automatic emergency alerts',
    ],
    cons: [
      'Very basic camera quality',
      'Limited storage (32GB)',
      'Requires Lively monthly plan',
      'Cannot run many popular apps',
    ],
    summary: 'The Jitterbug Smart4 is purpose-built for seniors with the simplest interface, biggest text, and best hearing aid support of any phone. If ease of use is your top priority, this is the one.',
  },
  {
    slug: 'consumer-cellular-iris-flip',
    name: 'Consumer Cellular Iris Flip',
    brand: 'Consumer Cellular',
    year: 2025,
    price: '$99',
    priceNum: 99,
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=400&fit=crop',
    screenSize: '2.8 inches (main)',
    weight: '130g',
    battery: 'Multi-day',
    os: 'Android',
    seniorScore: 8,
    easeOfUse: 9,
    screenReadability: 6,
    hearingAidRating: 'M4/T4',
    emergencySOS: true,
    fallDetection: false,
    voiceAssistant: 'Google Assistant',
    waterResistant: false,
    storage: '8GB',
    camera: '5MP single camera',
    bestFor: ['simplicity', 'hearing-aids', 'budget', 'first-smartphone', 'lightweight'],
    pros: [
      'Most affordable option at just $99',
      'Familiar flip phone design with physical buttons',
      'Ultra-lightweight at 130g',
      'Top hearing aid compatibility (M4/T4)',
      'SOS emergency button on the back',
    ],
    cons: [
      'Very small screen — hard for browsing',
      'Basic camera with low quality',
      'Very limited storage and app support',
      'No touchscreen — buttons only',
    ],
    summary: 'The Iris Flip is for seniors who want a simple, familiar flip phone with modern connectivity. At $99 with excellent hearing aid support, it is the simplest and most affordable option.',
  },
  {
    slug: 'iphone-15',
    name: 'Apple iPhone 15',
    brand: 'Apple',
    year: 2025,
    price: '$699',
    priceNum: 699,
    thumbnail: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=400&fit=crop',
    screenSize: '6.1 inches',
    weight: '171g',
    battery: 'All-day (20 hours)',
    os: 'iOS',
    seniorScore: 9,
    easeOfUse: 9,
    screenReadability: 8,
    hearingAidRating: 'M3/T4',
    emergencySOS: true,
    fallDetection: true,
    voiceAssistant: 'Siri',
    waterResistant: true,
    storage: '128GB',
    camera: '48MP dual camera',
    bestFor: ['simplicity', 'video-calls'],
    pros: [
      'Now $100 cheaper than at launch — great value',
      'Same proven iOS simplicity seniors love',
      'Fall detection and Emergency SOS included',
      'USB-C charging (same cable as many other devices)',
      'Excellent FaceTime video call quality',
    ],
    cons: [
      'Missing some newer AI features of iPhone 16',
      'Slightly shorter battery than iPhone 16',
      'Will receive fewer years of updates than newer models',
      'No Action Button (iPhone 16 feature)',
    ],
    summary: 'The iPhone 15 is a smart buy for seniors who want the full Apple experience at a reduced price. It still has fall detection, Emergency SOS, and the same intuitive interface as newer models.',
  },
  {
    slug: 'samsung-galaxy-s24-fe',
    name: 'Samsung Galaxy S24 FE',
    brand: 'Samsung',
    year: 2025,
    price: '$649',
    priceNum: 649,
    thumbnail: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&h=400&fit=crop',
    screenSize: '6.7 inches',
    weight: '213g',
    battery: 'All-day+ (4,700mAh)',
    os: 'Android',
    seniorScore: 8,
    easeOfUse: 7,
    screenReadability: 9,
    hearingAidRating: 'M3/T3',
    emergencySOS: true,
    fallDetection: false,
    voiceAssistant: 'Google Assistant + Galaxy AI',
    waterResistant: true,
    storage: '128GB',
    camera: '50MP triple camera',
    bestFor: ['big-screen', 'photography', 'long-battery'],
    pros: [
      'Large 6.7-inch display at a more affordable price',
      'Galaxy AI features for smart assistance',
      'Triple camera captures great photos',
      'Samsung Easy Mode for simplified interface',
      'Water and dust resistant',
    ],
    cons: [
      'Heavier at 213g',
      'No fall detection',
      'Fan Edition may feel less premium',
      'Samsung bloatware needs cleanup',
    ],
    summary: 'The Galaxy S24 FE delivers flagship Samsung features with a big screen and Galaxy AI at a friendlier price. A strong choice for seniors who want Android with AI smarts.',
  },
  {
    slug: 'google-pixel-7a',
    name: 'Google Pixel 7a',
    brand: 'Google',
    year: 2025,
    price: '$374',
    priceNum: 374,
    thumbnail: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=400&fit=crop',
    screenSize: '6.1 inches',
    weight: '193g',
    battery: 'All-day (24+ hours)',
    os: 'Android',
    seniorScore: 8,
    easeOfUse: 8,
    screenReadability: 8,
    hearingAidRating: 'M3/T3',
    emergencySOS: true,
    fallDetection: true,
    voiceAssistant: 'Google Assistant',
    waterResistant: true,
    storage: '128GB',
    camera: '64MP dual camera',
    bestFor: ['budget', 'simplicity', 'first-smartphone'],
    pros: [
      'Outstanding value — flagship features at budget price',
      'Clean Android with zero bloatware',
      'Fall detection and car crash detection',
      'Wireless charging included at this price',
      'Excellent Google Assistant integration',
    ],
    cons: [
      'Older model with fewer years of updates remaining',
      'Screen is slightly smaller at 6.1 inches',
      'No telephoto zoom camera',
      'Plastic back panel',
    ],
    summary: 'The Pixel 7a is an incredible budget option with fall detection, clean Android, and a great camera at under $400. Perfect for seniors wanting a no-nonsense smartphone.',
  },
  {
    slug: 'samsung-galaxy-z-flip-6',
    name: 'Samsung Galaxy Z Flip 6',
    brand: 'Samsung',
    year: 2025,
    price: '$1,099',
    priceNum: 1099,
    thumbnail: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&h=400&fit=crop',
    screenSize: '6.7 inches (foldable)',
    weight: '187g',
    battery: 'All-day (4,000mAh)',
    os: 'Android',
    seniorScore: 5,
    easeOfUse: 5,
    screenReadability: 8,
    hearingAidRating: 'M3/T3',
    emergencySOS: true,
    fallDetection: false,
    voiceAssistant: 'Google Assistant + Galaxy AI',
    waterResistant: true,
    storage: '256GB',
    camera: '50MP dual camera',
    bestFor: ['photography'],
    pros: [
      'Folds in half for easy pocket storage',
      'Outer screen shows notifications without opening',
      'Full-size 6.7-inch screen when unfolded',
      'Hands-free camera mode for selfies and video calls',
      'Nostalgic flip phone feel with modern features',
    ],
    cons: [
      'Very expensive at $1,099',
      'Folding mechanism adds complexity',
      'Crease visible on the screen',
      'No fall detection',
    ],
    summary: 'The Galaxy Z Flip 6 brings flip phone nostalgia to modern smartphones, but its high price and complexity make it harder to recommend for most seniors unless they specifically want the fold.',
  },
  {
    slug: 'iphone-16-pro',
    name: 'Apple iPhone 16 Pro',
    brand: 'Apple',
    year: 2025,
    price: '$999',
    priceNum: 999,
    thumbnail: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=400&fit=crop',
    screenSize: '6.3 inches',
    weight: '199g',
    battery: 'All-day+ (27 hours)',
    os: 'iOS',
    seniorScore: 8,
    easeOfUse: 9,
    screenReadability: 9,
    hearingAidRating: 'M3/T4',
    emergencySOS: true,
    fallDetection: true,
    voiceAssistant: 'Siri',
    waterResistant: true,
    storage: '128GB',
    camera: '48MP triple camera with 5x zoom',
    bestFor: ['photography', 'video-calls', 'long-battery'],
    pros: [
      'Best iPhone camera with 5x optical zoom',
      'Slightly larger screen than standard iPhone 16',
      'Always-on display shows time without waking phone',
      'Longest battery life of any 6.3-inch phone',
      'All safety features: fall detection, crash detection, SOS',
    ],
    cons: [
      'Expensive at $999',
      'Pro features may be unnecessary for basic use',
      'Heavier than standard iPhone 16',
      'Camera system can be complex to master',
    ],
    summary: 'The iPhone 16 Pro is for seniors who want the best camera and longest battery in a manageable size. Its always-on display and 5x zoom make it worth the premium for photography lovers.',
  },
  {
    slug: 'nothing-phone-2a',
    name: 'Nothing Phone (2a)',
    brand: 'Nothing',
    year: 2025,
    price: '$349',
    priceNum: 349,
    thumbnail: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400&h=400&fit=crop',
    screenSize: '6.7 inches',
    weight: '190g',
    battery: 'Two-day (5,000mAh)',
    os: 'Android',
    seniorScore: 6,
    easeOfUse: 6,
    screenReadability: 9,
    hearingAidRating: 'Compatible',
    emergencySOS: true,
    fallDetection: false,
    voiceAssistant: 'Google Assistant',
    waterResistant: false,
    storage: '128GB',
    camera: '50MP dual camera',
    bestFor: ['budget', 'big-screen', 'long-battery'],
    pros: [
      'Affordable at $349 with large AMOLED display',
      'Unique transparent back design',
      'Two-day battery life',
      'Clean, near-stock Android experience',
      'Smooth 120Hz display for comfortable scrolling',
    ],
    cons: [
      'Newer brand with less senior-focused support',
      'No fall detection or special safety features',
      'Not water resistant',
      'LED glyph lights on back can be confusing',
    ],
    summary: 'The Nothing Phone (2a) is a stylish budget option with a big screen and two-day battery. However, its lack of safety features and unfamiliar brand make other options better for most seniors.',
  },
]

// ── Helper Functions ─────────────────────────────────────────────────────────

export function getAllPhones(): Phone[] {
  return PHONES
}

export function getPhoneBySlug(slug: string): Phone | undefined {
  return PHONES.find((p) => p.slug === slug)
}

/** Generate all valid pairwise comparisons: cross-brand + interesting same-brand */
export function getComparisons(): { slugA: string; slugB: string }[] {
  const pairs: { slugA: string; slugB: string }[] = []
  const seen = new Set<string>()

  // Interesting same-brand pairs
  const sameBrandPairs = new Set([
    'iphone-16|iphone-16-plus',
    'iphone-16|iphone-se-4th-gen',
    'iphone-16|iphone-15',
    'iphone-16|iphone-16-pro',
    'iphone-16-plus|iphone-16-pro',
    'iphone-se-4th-gen|iphone-15',
    'iphone-15|iphone-16-pro',
    'samsung-galaxy-s25|samsung-galaxy-s25-ultra',
    'samsung-galaxy-s25|samsung-galaxy-a16',
    'samsung-galaxy-s25|samsung-galaxy-a36',
    'samsung-galaxy-s25|samsung-galaxy-s24-fe',
    'samsung-galaxy-s25|samsung-galaxy-z-flip-6',
    'samsung-galaxy-a16|samsung-galaxy-a36',
    'samsung-galaxy-s25-ultra|samsung-galaxy-z-flip-6',
    'samsung-galaxy-s24-fe|samsung-galaxy-a36',
    'google-pixel-9|google-pixel-9-pro',
    'google-pixel-9|google-pixel-8a',
    'google-pixel-9-pro|google-pixel-8a',
    'google-pixel-7a|google-pixel-8a',
    'google-pixel-7a|google-pixel-9',
    'motorola-moto-g-power-2025|motorola-edge-2025',
  ])

  for (let i = 0; i < PHONES.length; i++) {
    for (let j = i + 1; j < PHONES.length; j++) {
      const a = PHONES[i]
      const b = PHONES[j]
      const key = `${a.slug}|${b.slug}`

      if (a.brand !== b.brand || sameBrandPairs.has(key)) {
        if (!seen.has(key)) {
          seen.add(key)
          pairs.push({ slugA: a.slug, slugB: b.slug })
        }
      }
    }
  }

  return pairs
}

export function getBestPhonesFor(useCase: string): Phone[] {
  return PHONES
    .filter((p) => p.bestFor.includes(useCase))
    .sort((a, b) => b.seniorScore - a.seniorScore)
}

/** Get popular comparisons for the index page */
export function getPopularComparisons(): { slugA: string; slugB: string }[] {
  return [
    { slugA: 'iphone-16', slugB: 'samsung-galaxy-s25' },
    { slugA: 'iphone-se-4th-gen', slugB: 'google-pixel-8a' },
    { slugA: 'iphone-16-plus', slugB: 'samsung-galaxy-s25-ultra' },
    { slugA: 'lively-jitterbug-smart4', slugB: 'consumer-cellular-iris-flip' },
    { slugA: 'iphone-16', slugB: 'google-pixel-9' },
    { slugA: 'samsung-galaxy-a16', slugB: 'motorola-moto-g-power-2025' },
    { slugA: 'iphone-se-4th-gen', slugB: 'samsung-galaxy-a36' },
    { slugA: 'google-pixel-9', slugB: 'samsung-galaxy-s25' },
    { slugA: 'iphone-16', slugB: 'iphone-15' },
    { slugA: 'iphone-16-pro', slugB: 'samsung-galaxy-s25-ultra' },
    { slugA: 'samsung-galaxy-a36', slugB: 'google-pixel-7a' },
    { slugA: 'iphone-16', slugB: 'lively-jitterbug-smart4' },
  ]
}
