export interface StateProvider {
  name: string
  type: 'fiber' | 'cable' | 'DSL' | 'satellite' | '5G home internet' | 'fixed wireless'
  seniorDiscount: boolean
  startingPrice: string
  speeds: string
  seniorPlan?: string
}

export interface StateData {
  slug: string
  name: string
  abbreviation: string
  providers: StateProvider[]
  averagePrice: string
  fccLifelineAvailable: boolean
  tips: string[]
}

export const statesData: StateData[] = [
  {
    slug: 'alabama',
    name: 'Alabama',
    abbreviation: 'AL',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'CenturyLink', type: 'DSL', seniorDiscount: false, startingPrice: '$50/mo', speeds: '20-940 Mbps' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'Alabama seniors can apply for the FCC Lifeline program at local ALEA offices for a $9.25/mo discount.',
      'Many Alabama libraries offer free Wi-Fi and computer classes for seniors — check your county library system.',
      'Ask about bundling internet with a basic phone line to save $10-15/mo with AT&T or CenturyLink.',
    ],
  },
  {
    slug: 'alaska',
    name: 'Alaska',
    abbreviation: 'AK',
    providers: [
      { name: 'GCI', type: 'cable', seniorDiscount: false, startingPrice: '$65/mo', speeds: '100 Mbps - 2 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Starlink', type: 'satellite', seniorDiscount: false, startingPrice: '$120/mo', speeds: '25-220 Mbps' },
    ],
    averagePrice: '$78/mo',
    fccLifelineAvailable: true,
    tips: [
      'Alaska has higher internet costs than the lower 48 — satellite may be your only option in rural areas.',
      'GCI offers service in Anchorage, Fairbanks, and Juneau; rural areas often rely on satellite.',
      'Check with your local Native corporation — some offer subsidized internet programs for elders.',
    ],
  },
  {
    slug: 'arizona',
    name: 'Arizona',
    abbreviation: 'AZ',
    providers: [
      { name: 'Cox', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '100 Mbps - 2 Gbps', seniorPlan: 'Cox Connect2Compete: $9.95/mo for eligible low-income households' },
      { name: 'CenturyLink', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '200 Mbps - 940 Mbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Starlink', type: 'satellite', seniorDiscount: false, startingPrice: '$120/mo', speeds: '25-220 Mbps' },
    ],
    averagePrice: '$55/mo',
    fccLifelineAvailable: true,
    tips: [
      'Arizona seniors in the Phoenix metro area have the most provider options — compare before committing.',
      'Cox Connect2Compete is one of the best low-income programs available in the state.',
      'Many senior centers in Maricopa and Pima counties offer free internet access and digital literacy classes.',
    ],
  },
  {
    slug: 'arkansas',
    name: 'Arkansas',
    abbreviation: 'AR',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Suddenlink (Optimum)', type: 'cable', seniorDiscount: false, startingPrice: '$40/mo', speeds: '300 Mbps - 1 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'CenturyLink', type: 'DSL', seniorDiscount: false, startingPrice: '$50/mo', speeds: '20-100 Mbps' },
    ],
    averagePrice: '$49/mo',
    fccLifelineAvailable: true,
    tips: [
      'Arkansas has a state broadband office that can help seniors find the most affordable plan in their area.',
      'Rural Arkansas residents should check T-Mobile 5G coverage — it has expanded significantly since 2025.',
      'Contact the Arkansas Area Agency on Aging for help applying to the Lifeline program.',
    ],
  },
  {
    slug: 'california',
    name: 'California',
    abbreviation: 'CA',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'California has its own LifeLine program (California LifeLine) offering additional phone/internet discounts beyond the federal program.',
      'Comcast Internet Essentials is widely available and one of the cheapest options for qualifying California seniors.',
      'Many public libraries in LA, San Francisco, and San Diego counties loan Wi-Fi hotspots to seniors for free.',
    ],
  },
  {
    slug: 'colorado',
    name: 'Colorado',
    abbreviation: 'CO',
    providers: [
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'CenturyLink', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '200 Mbps - 940 Mbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Xtream (Mediacom)', type: 'cable', seniorDiscount: false, startingPrice: '$30/mo', speeds: '100 Mbps - 1 Gbps' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Colorado has several municipal broadband networks (like Fort Collins Connexion) offering competitive prices.',
      'Mountain communities often have limited options — check if Starlink or T-Mobile 5G covers your area.',
      'The Colorado Division of Aging and Adult Services can help connect you with internet assistance programs.',
    ],
  },
  {
    slug: 'connecticut',
    name: 'Connecticut',
    abbreviation: 'CT',
    providers: [
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Frontier', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '500 Mbps - 5 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Optimum', type: 'cable', seniorDiscount: false, startingPrice: '$40/mo', speeds: '300 Mbps - 1 Gbps' },
    ],
    averagePrice: '$53/mo',
    fccLifelineAvailable: true,
    tips: [
      'Connecticut seniors can get help applying for assistance through their local Area Agency on Aging.',
      'Frontier fiber is expanding in CT and offers price-for-life guarantees with no annual contracts.',
      'Many Connecticut senior centers offer free Wi-Fi and computer access during business hours.',
    ],
  },
  {
    slug: 'delaware',
    name: 'Delaware',
    abbreviation: 'DE',
    providers: [
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Verizon Fios', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '300 Mbps - 2.3 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Delaware is small enough that Verizon Fios covers most populated areas — check availability at your address.',
      'The Delaware Division of Services for Aging and Adults can help with digital access programs.',
      'New Castle County libraries offer free digital literacy courses designed for seniors.',
    ],
  },
  {
    slug: 'florida',
    name: 'Florida',
    abbreviation: 'FL',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Florida has one of the largest senior populations — providers actively compete for your business, so negotiate.',
      'T-Mobile 55+ plans are especially popular in Florida retirement communities.',
      'Check with your HOA or condo association — many have negotiated bulk internet rates for residents.',
    ],
  },
  {
    slug: 'georgia',
    name: 'Georgia',
    abbreviation: 'GA',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Google Fiber', type: 'fiber', seniorDiscount: false, startingPrice: '$70/mo', speeds: '1 Gbps - 8 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'Google Fiber is available in parts of Atlanta metro — it offers fast speeds with no data caps or contracts.',
      'Georgia seniors can apply for Lifeline through the Georgia Public Service Commission.',
      'The Atlanta Regional Commission offers free tech classes for seniors through their Aging & Health Services.',
    ],
  },
  {
    slug: 'hawaii',
    name: 'Hawaii',
    abbreviation: 'HI',
    providers: [
      { name: 'Hawaiian Telcom (Lumen)', type: 'fiber', seniorDiscount: false, startingPrice: '$60/mo', speeds: '200 Mbps - 1 Gbps' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$62/mo',
    fccLifelineAvailable: true,
    tips: [
      'Internet in Hawaii tends to be more expensive — compare plans carefully and ask about introductory rates.',
      'Hawaiian Telcom fiber is available on Oahu, Maui, and Big Island in major towns.',
      'The Hawaii Executive Office on Aging can connect you with technology assistance programs.',
    ],
  },
  {
    slug: 'idaho',
    name: 'Idaho',
    abbreviation: 'ID',
    providers: [
      { name: 'CenturyLink', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '200 Mbps - 940 Mbps' },
      { name: 'Sparklight', type: 'cable', seniorDiscount: false, startingPrice: '$40/mo', speeds: '100 Mbps - 1 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Ziply Fiber', type: 'fiber', seniorDiscount: false, startingPrice: '$20/mo', speeds: '50 Mbps - 5 Gbps' },
    ],
    averagePrice: '$48/mo',
    fccLifelineAvailable: true,
    tips: [
      'Ziply Fiber offers some of the lowest starting prices in the state — check if they serve your area.',
      'Rural Idaho residents should compare T-Mobile 5G and Starlink for home internet coverage.',
      'Idaho Commission on Aging can help with technology access and digital literacy resources.',
    ],
  },
  {
    slug: 'illinois',
    name: 'Illinois',
    abbreviation: 'IL',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Google Fiber', type: 'fiber', seniorDiscount: false, startingPrice: '$70/mo', speeds: '1 Gbps - 8 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Chicago residents have excellent provider choice — AT&T Fiber and Xfinity cover most neighborhoods.',
      'Illinois has a broadband equity program that helps low-income seniors get connected.',
      'Contact the Illinois Department on Aging for free digital literacy workshops near you.',
    ],
  },
  {
    slug: 'indiana',
    name: 'Indiana',
    abbreviation: 'IN',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Indiana seniors in the Indianapolis metro have the widest range of provider options.',
      'MetroNet fiber is expanding across Indiana and offers no-contract plans.',
      'The Indiana Family and Social Services Administration can help with Lifeline applications.',
    ],
  },
  {
    slug: 'iowa',
    name: 'Iowa',
    abbreviation: 'IA',
    providers: [
      { name: 'CenturyLink', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '200 Mbps - 940 Mbps' },
      { name: 'Mediacom', type: 'cable', seniorDiscount: false, startingPrice: '$30/mo', speeds: '100 Mbps - 1 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Windstream', type: 'DSL', seniorDiscount: false, startingPrice: '$40/mo', speeds: '25-200 Mbps' },
    ],
    averagePrice: '$45/mo',
    fccLifelineAvailable: true,
    tips: [
      'Iowa has many local telcos and co-ops that offer competitive broadband — check local options first.',
      'Mediacom offers one of the more affordable entry-level plans in the state.',
      'Iowa Department on Aging provides technology assistance through their local Area Agencies on Aging.',
    ],
  },
  {
    slug: 'kansas',
    name: 'Kansas',
    abbreviation: 'KS',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Google Fiber', type: 'fiber', seniorDiscount: false, startingPrice: '$70/mo', speeds: '1 Gbps - 8 Gbps' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'Google Fiber is available in Kansas City metro — one of the fastest and most reliable options.',
      'Rural Kansas areas should check for local cooperative ISPs that may offer better rates.',
      'Kansas Department for Aging and Disability Services can help with digital access resources.',
    ],
  },
  {
    slug: 'kentucky',
    name: 'Kentucky',
    abbreviation: 'KY',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Windstream', type: 'DSL', seniorDiscount: false, startingPrice: '$40/mo', speeds: '25-200 Mbps' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Kentucky has invested heavily in rural broadband — new fiber options are expanding statewide.',
      'Spectrum Internet Assist is widely available across Kentucky for qualifying seniors.',
      'Contact the Kentucky Department for Aging and Independent Living for tech assistance programs.',
    ],
  },
  {
    slug: 'louisiana',
    name: 'Louisiana',
    abbreviation: 'LA',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Cox', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '100 Mbps - 2 Gbps', seniorPlan: 'Cox Connect2Compete: $9.95/mo for eligible low-income households' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'Cox Connect2Compete is an excellent low-cost option for qualifying Louisiana seniors.',
      'New Orleans and Baton Rouge have the best provider competition — compare plans before signing up.',
      'Louisiana Governor\'s Office of Elderly Affairs can help connect seniors with internet assistance.',
    ],
  },
  {
    slug: 'maine',
    name: 'Maine',
    abbreviation: 'ME',
    providers: [
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'Consolidated Communications', type: 'fiber', seniorDiscount: false, startingPrice: '$40/mo', speeds: '50 Mbps - 1 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$55/mo',
    fccLifelineAvailable: true,
    tips: [
      'Maine is expanding fiber through the Maine Connectivity Authority — new options are coming to rural areas.',
      'Consolidated Communications is building out fiber across southern Maine.',
      'Maine\'s Office of Aging and Disability Services offers digital literacy resources for seniors.',
    ],
  },
  {
    slug: 'maryland',
    name: 'Maryland',
    abbreviation: 'MD',
    providers: [
      { name: 'Verizon Fios', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '300 Mbps - 2.3 Gbps' },
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Breezeline', type: 'cable', seniorDiscount: false, startingPrice: '$50/mo', speeds: '200 Mbps - 1 Gbps' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'Maryland seniors in the Baltimore-DC corridor have excellent fiber coverage from Verizon Fios.',
      'Comcast Internet Essentials is widely available for qualifying Maryland seniors.',
      'Maryland Department of Aging offers technology training through its Senior Centers statewide.',
    ],
  },
  {
    slug: 'massachusetts',
    name: 'Massachusetts',
    abbreviation: 'MA',
    providers: [
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Verizon Fios', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '300 Mbps - 2.3 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Starry Internet', type: 'fixed wireless', seniorDiscount: false, startingPrice: '$30/mo', speeds: '50-200 Mbps' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'Massachusetts has strong consumer protection laws — ISPs cannot charge early termination fees on month-to-month plans.',
      'Starry Internet is available in Boston metro and offers very affordable fixed wireless service.',
      'The Massachusetts Executive Office of Elder Affairs runs free Senior Planet technology programs.',
    ],
  },
  {
    slug: 'michigan',
    name: 'Michigan',
    abbreviation: 'MI',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Detroit and Grand Rapids have excellent broadband competition — compare at least 3 providers.',
      'Michigan AASA (Aging & Adult Services Agency) offers digital inclusion programs for seniors.',
      'Upper Peninsula residents may need to rely on satellite or fixed wireless options.',
    ],
  },
  {
    slug: 'minnesota',
    name: 'Minnesota',
    abbreviation: 'MN',
    providers: [
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'CenturyLink', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '200 Mbps - 940 Mbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'US Internet', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '100 Mbps - 10 Gbps' },
    ],
    averagePrice: '$48/mo',
    fccLifelineAvailable: true,
    tips: [
      'Minneapolis-St. Paul has great fiber options including US Internet and CenturyLink fiber.',
      'Minnesota has many local broadband cooperatives in rural areas — check blandin.org for a list.',
      'The Minnesota Board on Aging provides technology assistance through Senior LinkAge Line (1-800-333-2433).',
    ],
  },
  {
    slug: 'mississippi',
    name: 'Mississippi',
    abbreviation: 'MS',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Sparklight', type: 'cable', seniorDiscount: false, startingPrice: '$40/mo', speeds: '100 Mbps - 1 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'CenturyLink', type: 'DSL', seniorDiscount: false, startingPrice: '$50/mo', speeds: '20-100 Mbps' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Mississippi has the lowest broadband adoption rate among seniors — many assistance programs are available.',
      'AT&T Access is the most widely available low-income program in the state.',
      'Mississippi Division of Aging and Adult Services can connect you with local tech help.',
    ],
  },
  {
    slug: 'missouri',
    name: 'Missouri',
    abbreviation: 'MO',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'Google Fiber', type: 'fiber', seniorDiscount: false, startingPrice: '$70/mo', speeds: '1 Gbps - 8 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'Google Fiber is available in Kansas City metro (both KS and MO sides) — check your address.',
      'Missouri seniors in St. Louis have good AT&T Fiber and Spectrum coverage.',
      'Missouri Division of Senior and Disability Services provides digital literacy assistance.',
    ],
  },
  {
    slug: 'montana',
    name: 'Montana',
    abbreviation: 'MT',
    providers: [
      { name: 'CenturyLink', type: 'DSL', seniorDiscount: false, startingPrice: '$50/mo', speeds: '20-140 Mbps' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Starlink', type: 'satellite', seniorDiscount: false, startingPrice: '$120/mo', speeds: '25-220 Mbps' },
    ],
    averagePrice: '$58/mo',
    fccLifelineAvailable: true,
    tips: [
      'Montana is vast and rural — Starlink may be the best option for seniors outside major towns.',
      'Check for local cooperatives like Blackfoot Communications for competitive rural broadband.',
      'Montana Senior and Long Term Care Division can help with internet access resources.',
    ],
  },
  {
    slug: 'nebraska',
    name: 'Nebraska',
    abbreviation: 'NE',
    providers: [
      { name: 'Cox', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '100 Mbps - 2 Gbps', seniorPlan: 'Cox Connect2Compete: $9.95/mo for eligible low-income households' },
      { name: 'CenturyLink', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '200 Mbps - 940 Mbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Windstream', type: 'DSL', seniorDiscount: false, startingPrice: '$40/mo', speeds: '25-200 Mbps' },
    ],
    averagePrice: '$48/mo',
    fccLifelineAvailable: true,
    tips: [
      'Omaha and Lincoln have excellent Cox and CenturyLink fiber coverage.',
      'Nebraska has many rural telephone cooperatives offering affordable broadband.',
      'Nebraska State Unit on Aging provides technology assistance through local agencies.',
    ],
  },
  {
    slug: 'nevada',
    name: 'Nevada',
    abbreviation: 'NV',
    providers: [
      { name: 'Cox', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '100 Mbps - 2 Gbps', seniorPlan: 'Cox Connect2Compete: $9.95/mo for eligible low-income households' },
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'CenturyLink', type: 'DSL', seniorDiscount: false, startingPrice: '$50/mo', speeds: '20-100 Mbps' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'Las Vegas and Reno have strong Cox cable and T-Mobile 5G coverage.',
      'Nevada seniors in retirement communities should ask about bulk internet rates negotiated by their HOA.',
      'Nevada Aging and Disability Services Division can help with internet assistance applications.',
    ],
  },
  {
    slug: 'new-hampshire',
    name: 'New Hampshire',
    abbreviation: 'NH',
    providers: [
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Consolidated Communications', type: 'fiber', seniorDiscount: false, startingPrice: '$40/mo', speeds: '50 Mbps - 1 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'New Hampshire is investing in rural broadband through its broadband matching grant program.',
      'Consolidated Communications is expanding fiber across southern NH.',
      'NH Bureau of Elderly and Adult Services can connect you with digital access programs.',
    ],
  },
  {
    slug: 'new-jersey',
    name: 'New Jersey',
    abbreviation: 'NJ',
    providers: [
      { name: 'Verizon Fios', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '300 Mbps - 2.3 Gbps' },
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Optimum', type: 'cable', seniorDiscount: false, startingPrice: '$40/mo', speeds: '300 Mbps - 1 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'New Jersey has excellent Verizon Fios coverage — it is available in most of the state.',
      'NJ has its own Lifeline program with additional state credits beyond the federal benefit.',
      'NJ Division of Aging Services runs tech training programs at senior centers across the state.',
    ],
  },
  {
    slug: 'new-mexico',
    name: 'New Mexico',
    abbreviation: 'NM',
    providers: [
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'CenturyLink', type: 'DSL', seniorDiscount: false, startingPrice: '$50/mo', speeds: '20-140 Mbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Starlink', type: 'satellite', seniorDiscount: false, startingPrice: '$120/mo', speeds: '25-220 Mbps' },
    ],
    averagePrice: '$55/mo',
    fccLifelineAvailable: true,
    tips: [
      'New Mexico has significant rural areas — check T-Mobile 5G and Starlink coverage maps.',
      'Albuquerque and Santa Fe have the most broadband options in the state.',
      'New Mexico Aging and Long-Term Services Department offers technology assistance for seniors.',
    ],
  },
  {
    slug: 'new-york',
    name: 'New York',
    abbreviation: 'NY',
    providers: [
      { name: 'Verizon Fios', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '300 Mbps - 2.3 Gbps' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'Optimum', type: 'cable', seniorDiscount: false, startingPrice: '$40/mo', speeds: '300 Mbps - 1 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'New York City residents can access free public Wi-Fi through LinkNYC kiosks across all five boroughs.',
      'New York State has a broadband assistance program — contact your local Department of Social Services.',
      'The NYC Department for the Aging runs free computer and internet classes for seniors at senior centers.',
    ],
  },
  {
    slug: 'north-carolina',
    name: 'North Carolina',
    abbreviation: 'NC',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'Google Fiber', type: 'fiber', seniorDiscount: false, startingPrice: '$70/mo', speeds: '1 Gbps - 8 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'Google Fiber is available in Charlotte and the Research Triangle (Raleigh-Durham).',
      'North Carolina has a statewide broadband initiative bringing fiber to underserved rural areas.',
      'NC Division of Aging and Adult Services provides digital literacy programs for seniors.',
    ],
  },
  {
    slug: 'north-dakota',
    name: 'North Dakota',
    abbreviation: 'ND',
    providers: [
      { name: 'Midco', type: 'cable', seniorDiscount: false, startingPrice: '$40/mo', speeds: '100 Mbps - 2 Gbps' },
      { name: 'CenturyLink', type: 'DSL', seniorDiscount: false, startingPrice: '$50/mo', speeds: '20-100 Mbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$48/mo',
    fccLifelineAvailable: true,
    tips: [
      'North Dakota has many local telephone cooperatives offering broadband at competitive rates.',
      'Midco is the largest cable provider in ND and covers Fargo, Bismarck, and surrounding areas.',
      'ND Aging Services Division can help connect seniors with internet assistance programs.',
    ],
  },
  {
    slug: 'ohio',
    name: 'Ohio',
    abbreviation: 'OH',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Ohio has strong provider competition in major cities — Cleveland, Columbus, and Cincinnati all have 4+ options.',
      'Ohio BroadbandOhio initiative is expanding fiber to rural communities.',
      'Ohio Department of Aging runs the SAGE (Senior Advocates for Generational Equity) program with tech training.',
    ],
  },
  {
    slug: 'oklahoma',
    name: 'Oklahoma',
    abbreviation: 'OK',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Cox', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '100 Mbps - 2 Gbps', seniorPlan: 'Cox Connect2Compete: $9.95/mo for eligible low-income households' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Windstream', type: 'DSL', seniorDiscount: false, startingPrice: '$40/mo', speeds: '25-200 Mbps' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Oklahoma City and Tulsa have the widest range of broadband options in the state.',
      'Cox Connect2Compete is an excellent low-cost option for qualifying Oklahoma seniors.',
      'Oklahoma Aging Services Division provides resources for seniors getting online.',
    ],
  },
  {
    slug: 'oregon',
    name: 'Oregon',
    abbreviation: 'OR',
    providers: [
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'CenturyLink', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '200 Mbps - 940 Mbps' },
      { name: 'Ziply Fiber', type: 'fiber', seniorDiscount: false, startingPrice: '$20/mo', speeds: '50 Mbps - 5 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$48/mo',
    fccLifelineAvailable: true,
    tips: [
      'Ziply Fiber offers some of the lowest starting prices in Oregon — starting at $20/mo for 50 Mbps.',
      'Portland metro has excellent broadband competition — compare Xfinity, CenturyLink, and Ziply.',
      'Oregon Department of Human Services Aging and People with Disabilities division offers tech resources.',
    ],
  },
  {
    slug: 'pennsylvania',
    name: 'Pennsylvania',
    abbreviation: 'PA',
    providers: [
      { name: 'Verizon Fios', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '300 Mbps - 2.3 Gbps' },
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Windstream', type: 'DSL', seniorDiscount: false, startingPrice: '$40/mo', speeds: '25-200 Mbps' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Philadelphia is Comcast\'s headquarters — Internet Essentials is widely available and well-supported here.',
      'Verizon Fios covers most of eastern PA; western PA relies more on Xfinity and Windstream.',
      'Pennsylvania Department of Aging runs free Apprise counseling that can help with internet assistance.',
    ],
  },
  {
    slug: 'rhode-island',
    name: 'Rhode Island',
    abbreviation: 'RI',
    providers: [
      { name: 'Cox', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '100 Mbps - 2 Gbps', seniorPlan: 'Cox Connect2Compete: $9.95/mo for eligible low-income households' },
      { name: 'Verizon Fios', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '300 Mbps - 2.3 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'Rhode Island is small enough that most addresses have both Cox and Verizon Fios available.',
      'Cox Connect2Compete is widely available for qualifying Rhode Island seniors.',
      'RI Division of Elderly Affairs can connect you with digital literacy and internet assistance programs.',
    ],
  },
  {
    slug: 'south-carolina',
    name: 'South Carolina',
    abbreviation: 'SC',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Google Fiber', type: 'fiber', seniorDiscount: false, startingPrice: '$70/mo', speeds: '1 Gbps - 8 Gbps' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'Google Fiber is expanding in parts of South Carolina including the Charleston metro area.',
      'Spectrum Internet Assist is widely available across the state for qualifying seniors.',
      'SC Lieutenant Governor\'s Office on Aging provides technology assistance through regional AAAs.',
    ],
  },
  {
    slug: 'south-dakota',
    name: 'South Dakota',
    abbreviation: 'SD',
    providers: [
      { name: 'Midco', type: 'cable', seniorDiscount: false, startingPrice: '$40/mo', speeds: '100 Mbps - 2 Gbps' },
      { name: 'CenturyLink', type: 'DSL', seniorDiscount: false, startingPrice: '$50/mo', speeds: '20-100 Mbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Starlink', type: 'satellite', seniorDiscount: false, startingPrice: '$120/mo', speeds: '25-220 Mbps' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'Sioux Falls and Rapid City have the most broadband options; rural areas may need satellite.',
      'South Dakota has many local telephone cooperatives offering competitive broadband rates.',
      'SD Department of Human Services Aging Services can help seniors find internet assistance.',
    ],
  },
  {
    slug: 'tennessee',
    name: 'Tennessee',
    abbreviation: 'TN',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Chattanooga\'s EPB offers 10 Gbps fiber — one of the fastest municipal networks in the US.',
      'Nashville and Memphis have strong AT&T Fiber and Xfinity coverage.',
      'Tennessee Commission on Aging and Disability can connect seniors with internet assistance.',
    ],
  },
  {
    slug: 'texas',
    name: 'Texas',
    abbreviation: 'TX',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'Google Fiber', type: 'fiber', seniorDiscount: false, startingPrice: '$70/mo', speeds: '1 Gbps - 8 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$52/mo',
    fccLifelineAvailable: true,
    tips: [
      'Texas is a deregulated market with many providers — always compare at least 3-4 options at your address.',
      'Google Fiber is available in Austin, San Antonio, and parts of DFW.',
      'Texas Health and Human Services Commission can help seniors apply for the Lifeline program.',
    ],
  },
  {
    slug: 'utah',
    name: 'Utah',
    abbreviation: 'UT',
    providers: [
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Google Fiber', type: 'fiber', seniorDiscount: false, startingPrice: '$70/mo', speeds: '1 Gbps - 8 Gbps' },
      { name: 'CenturyLink', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '200 Mbps - 940 Mbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'UTOPIA Fiber is a municipal network available in many Utah cities with multiple provider options.',
      'Google Fiber is available in the Salt Lake City metro and Provo areas.',
      'Utah Division of Aging and Adult Services provides digital literacy resources for seniors.',
    ],
  },
  {
    slug: 'vermont',
    name: 'Vermont',
    abbreviation: 'VT',
    providers: [
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Consolidated Communications', type: 'fiber', seniorDiscount: false, startingPrice: '$40/mo', speeds: '50 Mbps - 1 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Starlink', type: 'satellite', seniorDiscount: false, startingPrice: '$120/mo', speeds: '25-220 Mbps' },
    ],
    averagePrice: '$55/mo',
    fccLifelineAvailable: true,
    tips: [
      'Vermont\'s Communications Union Districts are building fiber to unserved areas — check if your town participates.',
      'Rural Vermont residents may find Starlink to be the most reliable high-speed option.',
      'Vermont Department of Disabilities, Aging and Independent Living offers tech assistance programs.',
    ],
  },
  {
    slug: 'virginia',
    name: 'Virginia',
    abbreviation: 'VA',
    providers: [
      { name: 'Verizon Fios', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '300 Mbps - 2.3 Gbps' },
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Cox', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '100 Mbps - 2 Gbps', seniorPlan: 'Cox Connect2Compete: $9.95/mo for eligible low-income households' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Northern Virginia has some of the best internet infrastructure in the US — Verizon Fios dominates here.',
      'Cox serves the Hampton Roads/Virginia Beach area with competitive plans.',
      'Virginia Department for Aging and Rehabilitative Services provides digital inclusion resources.',
    ],
  },
  {
    slug: 'washington',
    name: 'Washington',
    abbreviation: 'WA',
    providers: [
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'CenturyLink', type: 'fiber', seniorDiscount: false, startingPrice: '$50/mo', speeds: '200 Mbps - 940 Mbps' },
      { name: 'Ziply Fiber', type: 'fiber', seniorDiscount: false, startingPrice: '$20/mo', speeds: '50 Mbps - 5 Gbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
    ],
    averagePrice: '$48/mo',
    fccLifelineAvailable: true,
    tips: [
      'Ziply Fiber offers excellent value in Washington state — check their $20/mo starter plan.',
      'Seattle metro has the most provider options; eastern Washington is more limited.',
      'Washington Aging and Long-Term Support Administration provides tech resources for seniors.',
    ],
  },
  {
    slug: 'west-virginia',
    name: 'West Virginia',
    abbreviation: 'WV',
    providers: [
      { name: 'Xfinity (Comcast)', type: 'cable', seniorDiscount: true, startingPrice: '$35/mo', speeds: '75 Mbps - 2 Gbps', seniorPlan: 'Internet Essentials: $9.95/mo for qualifying seniors on SSI' },
      { name: 'Frontier', type: 'DSL', seniorDiscount: false, startingPrice: '$38/mo', speeds: '25-115 Mbps' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Starlink', type: 'satellite', seniorDiscount: false, startingPrice: '$120/mo', speeds: '25-220 Mbps' },
    ],
    averagePrice: '$55/mo',
    fccLifelineAvailable: true,
    tips: [
      'West Virginia has a broadband expansion program investing in fiber for rural communities.',
      'Mountain areas may need satellite — Starlink offers the most reliable rural option.',
      'WV Bureau of Senior Services can help with internet access and digital literacy programs.',
    ],
  },
  {
    slug: 'wisconsin',
    name: 'Wisconsin',
    abbreviation: 'WI',
    providers: [
      { name: 'AT&T', type: 'fiber', seniorDiscount: true, startingPrice: '$55/mo', speeds: '300 Mbps - 5 Gbps', seniorPlan: 'AT&T Access: $30/mo for qualifying low-income households' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '72-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'TDS Telecom', type: 'fiber', seniorDiscount: false, startingPrice: '$40/mo', speeds: '100 Mbps - 2 Gbps' },
    ],
    averagePrice: '$50/mo',
    fccLifelineAvailable: true,
    tips: [
      'Milwaukee and Madison have the best broadband competition in Wisconsin.',
      'TDS Telecom is expanding fiber across many Wisconsin communities.',
      'Wisconsin Bureau of Aging and Disability Resources can help with internet access programs.',
    ],
  },
  {
    slug: 'wyoming',
    name: 'Wyoming',
    abbreviation: 'WY',
    providers: [
      { name: 'CenturyLink', type: 'DSL', seniorDiscount: false, startingPrice: '$50/mo', speeds: '20-100 Mbps' },
      { name: 'Spectrum', type: 'cable', seniorDiscount: true, startingPrice: '$50/mo', speeds: '300 Mbps - 1 Gbps', seniorPlan: 'Spectrum Internet Assist: $17.99/mo for eligible seniors 65+' },
      { name: 'T-Mobile Home Internet', type: '5G home internet', seniorDiscount: true, startingPrice: '$50/mo', speeds: '33-245 Mbps', seniorPlan: 'T-Mobile 55+: discounted plans for customers 55 and older' },
      { name: 'Starlink', type: 'satellite', seniorDiscount: false, startingPrice: '$120/mo', speeds: '25-220 Mbps' },
    ],
    averagePrice: '$58/mo',
    fccLifelineAvailable: true,
    tips: [
      'Wyoming is one of the most rural states — Starlink and T-Mobile 5G are expanding coverage.',
      'Casper and Cheyenne have the most broadband options; rural areas are limited.',
      'Wyoming Department of Health Aging Division can connect seniors with internet assistance.',
    ],
  },
]

// Neighboring/related states for cross-linking
export const stateNeighbors: Record<string, string[]> = {
  'alabama': ['florida', 'georgia', 'tennessee', 'mississippi'],
  'alaska': ['washington', 'hawaii'],
  'arizona': ['california', 'nevada', 'utah', 'colorado', 'new-mexico'],
  'arkansas': ['texas', 'oklahoma', 'missouri', 'tennessee', 'mississippi', 'louisiana'],
  'california': ['oregon', 'nevada', 'arizona'],
  'colorado': ['utah', 'wyoming', 'nebraska', 'kansas', 'new-mexico', 'arizona'],
  'connecticut': ['new-york', 'massachusetts', 'rhode-island'],
  'delaware': ['maryland', 'new-jersey', 'pennsylvania'],
  'florida': ['georgia', 'alabama'],
  'georgia': ['florida', 'alabama', 'tennessee', 'north-carolina', 'south-carolina'],
  'hawaii': ['california', 'alaska'],
  'idaho': ['washington', 'oregon', 'montana', 'wyoming', 'utah', 'nevada'],
  'illinois': ['wisconsin', 'indiana', 'iowa', 'missouri', 'kentucky'],
  'indiana': ['illinois', 'michigan', 'ohio', 'kentucky'],
  'iowa': ['minnesota', 'wisconsin', 'illinois', 'missouri', 'nebraska', 'south-dakota'],
  'kansas': ['nebraska', 'missouri', 'oklahoma', 'colorado'],
  'kentucky': ['indiana', 'ohio', 'west-virginia', 'virginia', 'tennessee'],
  'louisiana': ['texas', 'arkansas', 'mississippi'],
  'maine': ['new-hampshire', 'massachusetts', 'vermont'],
  'maryland': ['virginia', 'west-virginia', 'pennsylvania', 'delaware'],
  'massachusetts': ['connecticut', 'rhode-island', 'new-hampshire', 'vermont', 'new-york'],
  'michigan': ['ohio', 'indiana', 'wisconsin'],
  'minnesota': ['wisconsin', 'iowa', 'north-dakota', 'south-dakota'],
  'mississippi': ['alabama', 'tennessee', 'arkansas', 'louisiana'],
  'missouri': ['iowa', 'illinois', 'kentucky', 'tennessee', 'arkansas', 'oklahoma', 'kansas', 'nebraska'],
  'montana': ['north-dakota', 'south-dakota', 'wyoming', 'idaho'],
  'nebraska': ['south-dakota', 'iowa', 'missouri', 'kansas', 'colorado', 'wyoming'],
  'nevada': ['california', 'oregon', 'idaho', 'utah', 'arizona'],
  'new-hampshire': ['vermont', 'maine', 'massachusetts'],
  'new-jersey': ['new-york', 'pennsylvania', 'delaware'],
  'new-mexico': ['arizona', 'colorado', 'oklahoma', 'texas'],
  'new-york': ['new-jersey', 'connecticut', 'massachusetts', 'vermont', 'pennsylvania'],
  'north-carolina': ['virginia', 'tennessee', 'georgia', 'south-carolina'],
  'north-dakota': ['montana', 'south-dakota', 'minnesota'],
  'ohio': ['michigan', 'indiana', 'kentucky', 'west-virginia', 'pennsylvania'],
  'oklahoma': ['texas', 'arkansas', 'missouri', 'kansas', 'colorado', 'new-mexico'],
  'oregon': ['washington', 'california', 'idaho', 'nevada'],
  'pennsylvania': ['new-york', 'new-jersey', 'delaware', 'maryland', 'west-virginia', 'ohio'],
  'rhode-island': ['connecticut', 'massachusetts'],
  'south-carolina': ['north-carolina', 'georgia'],
  'south-dakota': ['north-dakota', 'minnesota', 'iowa', 'nebraska', 'wyoming', 'montana'],
  'tennessee': ['kentucky', 'virginia', 'north-carolina', 'georgia', 'alabama', 'mississippi', 'arkansas', 'missouri'],
  'texas': ['new-mexico', 'oklahoma', 'arkansas', 'louisiana'],
  'utah': ['idaho', 'wyoming', 'colorado', 'arizona', 'nevada'],
  'vermont': ['new-hampshire', 'massachusetts', 'new-york'],
  'virginia': ['maryland', 'west-virginia', 'kentucky', 'tennessee', 'north-carolina'],
  'washington': ['oregon', 'idaho'],
  'west-virginia': ['ohio', 'pennsylvania', 'maryland', 'virginia', 'kentucky'],
  'wisconsin': ['minnesota', 'iowa', 'illinois', 'michigan'],
  'wyoming': ['montana', 'south-dakota', 'nebraska', 'colorado', 'utah', 'idaho'],
}
