// ── Tech Support Hotline Finder — Company Database ──────────────────────────

export type SupportCategory =
  | 'phone-manufacturer'
  | 'carrier'
  | 'streaming'
  | 'social-media'
  | 'email'
  | 'banking'
  | 'shopping'
  | 'smart-home'
  | 'computer'
  | 'government'
  | 'security'
  | 'internet-provider'
  | 'software'

export interface SupportEntry {
  slug: string
  name: string
  category: SupportCategory
  phoneNumber: string | null
  phoneNumberUS: string | null
  phoneNumberUK: string | null
  chatUrl: string | null
  supportUrl: string
  hours: string
  avgWaitTime: string
  tipsToReachHuman: string[]
  seniorSupport: boolean
  seniorLine: string | null
  description: string
  logo: string
}

export interface SupportCategoryInfo {
  slug: SupportCategory
  label: string
  icon: string
  description: string
}

// ── Categories ──────────────────────────────────────────────────────────────

export const SUPPORT_CATEGORIES: SupportCategoryInfo[] = [
  {
    slug: 'phone-manufacturer',
    label: 'Phone Manufacturers',
    icon: '📱',
    description: 'Get help with your smartphone from Apple, Samsung, Google, and more.',
  },
  {
    slug: 'carrier',
    label: 'Phone Carriers',
    icon: '📶',
    description: 'Support for your cell phone plan, billing, and network issues.',
  },
  {
    slug: 'streaming',
    label: 'Streaming Services',
    icon: '📺',
    description: 'Help with Netflix, Hulu, Disney+, and other streaming apps.',
  },
  {
    slug: 'social-media',
    label: 'Social Media',
    icon: '💬',
    description: 'Get help with Facebook, Instagram, WhatsApp, YouTube, and more.',
  },
  {
    slug: 'email',
    label: 'Email Providers',
    icon: '📧',
    description: 'Support for Gmail, Yahoo Mail, Outlook, and AOL email accounts.',
  },
  {
    slug: 'banking',
    label: 'Banking & Finance',
    icon: '🏦',
    description: 'Customer service for banks, credit cards, and payment services.',
  },
  {
    slug: 'shopping',
    label: 'Online Shopping',
    icon: '🛒',
    description: 'Help with orders, returns, and accounts on Amazon, Walmart, and more.',
  },
  {
    slug: 'smart-home',
    label: 'Smart Home',
    icon: '🏠',
    description: 'Support for Alexa, Google Home, Ring, Nest, and smart home devices.',
  },
  {
    slug: 'computer',
    label: 'Computers & Software',
    icon: '💻',
    description: 'Help with Windows, Mac, HP, Dell, and Lenovo computers.',
  },
  {
    slug: 'government',
    label: 'Government & Utilities',
    icon: '🏛️',
    description: 'Contact Medicare, Social Security, IRS, USPS, and DMV by phone.',
  },
  {
    slug: 'security',
    label: 'Security & Antivirus',
    icon: '🔒',
    description: 'Support for Norton, McAfee, LifeLock, and identity protection services.',
  },
  {
    slug: 'internet-provider',
    label: 'Internet Providers',
    icon: '🌐',
    description: 'Help with your home internet, WiFi, and broadband service.',
  },
  {
    slug: 'software',
    label: 'Software',
    icon: '⚙️',
    description: 'Help with popular software applications and digital tools.',
  },
]

// ── Full Company Database ───────────────────────────────────────────────────

export const SUPPORT_DATABASE: SupportEntry[] = [
  // ─── Phone Manufacturers (10) ──────────────────────────────────────────
  {
    slug: 'apple-iphone',
    name: 'Apple iPhone',
    category: 'phone-manufacturer',
    phoneNumber: '1-800-275-2273',
    phoneNumberUS: '1-800-275-2273',
    phoneNumberUK: '0800-048-0408',
    chatUrl: 'https://support.apple.com/contact',
    supportUrl: 'https://support.apple.com/iphone',
    hours: 'Mon-Sun 8am-8pm local time',
    avgWaitTime: '5-10 min',
    tipsToReachHuman: [
      'Say "speak to a representative" at any time',
      'Press 0 twice to skip the automated menu',
      'Select "other issues" if your problem is not listed',
      'Have your iPhone serial number ready for faster service',
    ],
    seniorSupport: true,
    seniorLine: '1-800-275-2273',
    description: 'Apple support helps with iPhone setup, software updates, iCloud, Apple ID, battery issues, and hardware repairs.',
    logo: '🍎',
  },
  {
    slug: 'samsung',
    name: 'Samsung',
    category: 'phone-manufacturer',
    phoneNumber: '1-800-726-7864',
    phoneNumberUS: '1-800-726-7864',
    phoneNumberUK: '0330-726-7864',
    chatUrl: 'https://www.samsung.com/us/support/contact/',
    supportUrl: 'https://www.samsung.com/us/support/',
    hours: '24/7',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Press 1 for mobile, then 0 for an agent',
      'Say "representative" at the voice prompt',
      'Select "other" if your issue is not in the menu',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Samsung support covers Galaxy phones, tablets, TVs, and appliances including setup, troubleshooting, and warranty claims.',
    logo: 'S',
  },
  {
    slug: 'google-pixel',
    name: 'Google Pixel',
    category: 'phone-manufacturer',
    phoneNumber: '1-855-836-3987',
    phoneNumberUS: '1-855-836-3987',
    phoneNumberUK: '0800-328-8238',
    chatUrl: 'https://support.google.com/googlepixelphone/gethelp',
    supportUrl: 'https://support.google.com/googlepixelphone/',
    hours: '24/7',
    avgWaitTime: '5-10 min',
    tipsToReachHuman: [
      'Press 0 at any point in the menu',
      'Say "talk to someone" at the voice prompt',
      'Use the Google Fi app to request a callback',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Google Pixel support helps with phone setup, Android updates, Google account issues, and hardware problems.',
    logo: 'G',
  },
  {
    slug: 'motorola',
    name: 'Motorola',
    category: 'phone-manufacturer',
    phoneNumber: '1-800-734-5870',
    phoneNumberUS: '1-800-734-5870',
    phoneNumberUK: '0800-953-0168',
    chatUrl: 'https://www.motorola.com/us/support',
    supportUrl: 'https://www.motorola.com/us/support',
    hours: 'Mon-Fri 8am-10pm ET, Sat-Sun 10am-8pm ET',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 to skip the automated system',
      'Select "technical support" from the menu',
      'Have your phone model and IMEI ready',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Motorola supports Moto G, Moto Edge, and Razr phones with help for setup, software, and repairs.',
    logo: 'M',
  },
  {
    slug: 'lg-phones',
    name: 'LG',
    category: 'phone-manufacturer',
    phoneNumber: '1-800-243-0000',
    phoneNumberUS: '1-800-243-0000',
    phoneNumberUK: '0344-847-5454',
    chatUrl: 'https://www.lg.com/us/support/contact',
    supportUrl: 'https://www.lg.com/us/support',
    hours: 'Mon-Fri 8am-9pm ET, Sat-Sun 9am-6pm ET',
    avgWaitTime: '10-15 min',
    tipsToReachHuman: [
      'Press 0 repeatedly to reach an agent',
      'Say "agent" at the voice prompt',
      'Select "mobile phones" then "other" for fastest routing',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'LG support covers phones, TVs, and appliances. Note: LG exited the phone market in 2021 but still offers software support.',
    logo: 'L',
  },
  {
    slug: 'oneplus',
    name: 'OnePlus',
    category: 'phone-manufacturer',
    phoneNumber: '1-833-777-3633',
    phoneNumberUS: '1-833-777-3633',
    phoneNumberUK: null,
    chatUrl: 'https://www.oneplus.com/support',
    supportUrl: 'https://www.oneplus.com/support',
    hours: 'Mon-Fri 9am-9pm ET',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 2 for technical support then 0 for agent',
      'Use the live chat on their website for faster help',
      'Have your order number or device serial ready',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'OnePlus provides support for their Android phones including setup, OxygenOS updates, and hardware issues.',
    logo: '1',
  },
  {
    slug: 'nokia',
    name: 'Nokia',
    category: 'phone-manufacturer',
    phoneNumber: '1-888-665-4228',
    phoneNumberUS: '1-888-665-4228',
    phoneNumberUK: '0800-030-4578',
    chatUrl: 'https://www.nokia.com/phones/support',
    supportUrl: 'https://www.nokia.com/phones/support',
    hours: 'Mon-Fri 9am-6pm ET',
    avgWaitTime: '10-15 min',
    tipsToReachHuman: [
      'Press 0 at the main menu',
      'Say "representative" when prompted',
      'Select "other issue" from the options',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Nokia supports their smartphones and feature phones with help for Android updates, setup, and basic troubleshooting.',
    logo: 'N',
  },
  {
    slug: 'sony-xperia',
    name: 'Sony Xperia',
    category: 'phone-manufacturer',
    phoneNumber: '1-866-766-9374',
    phoneNumberUS: '1-866-766-9374',
    phoneNumberUK: '0344-846-0000',
    chatUrl: 'https://www.sony.com/en/contact-us',
    supportUrl: 'https://www.sony.com/en/support',
    hours: 'Mon-Fri 9am-6pm ET',
    avgWaitTime: '15-25 min',
    tipsToReachHuman: [
      'Press 3 for mobile products, then 0 for agent',
      'Say "operator" at any time',
      'Try calling early morning for shorter waits',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Sony provides support for Xperia smartphones, including camera features, Android updates, and warranty service.',
    logo: 'S',
  },
  {
    slug: 'consumer-cellular',
    name: 'Consumer Cellular',
    category: 'phone-manufacturer',
    phoneNumber: '1-888-345-5509',
    phoneNumberUS: '1-888-345-5509',
    phoneNumberUK: null,
    chatUrl: 'https://www.consumercellular.com/contact',
    supportUrl: 'https://www.consumercellular.com/support',
    hours: 'Mon-Fri 6am-8pm PT, Sat-Sun 6am-5pm PT',
    avgWaitTime: '5-10 min',
    tipsToReachHuman: [
      'Press 0 to immediately reach an agent',
      'They are known for excellent customer service with minimal wait',
      'Mention you are a new customer for priority routing',
      'AARP members get dedicated support',
    ],
    seniorSupport: true,
    seniorLine: '1-888-345-5509',
    description: 'Consumer Cellular specializes in affordable plans and phones for seniors. Their US-based support is known for patience and clarity.',
    logo: 'C',
  },
  {
    slug: 'lively-jitterbug',
    name: 'Lively (Jitterbug)',
    category: 'phone-manufacturer',
    phoneNumber: '1-800-733-6632',
    phoneNumberUS: '1-800-733-6632',
    phoneNumberUK: null,
    chatUrl: null,
    supportUrl: 'https://www.lively.com/support',
    hours: 'Mon-Sun 5am-9pm PT',
    avgWaitTime: '3-8 min',
    tipsToReachHuman: [
      'Press the dedicated "Operator" button on your Jitterbug phone',
      'Call and simply wait — they connect you quickly',
      'Their agents are specially trained to assist seniors',
    ],
    seniorSupport: true,
    seniorLine: '1-800-733-6632',
    description: 'Lively (formerly Jitterbug) is designed specifically for seniors with simple phones, urgent response services, and patient US-based support.',
    logo: 'L',
  },

  // ─── Carriers (10) ────────────────────────────────────────────────────
  {
    slug: 'verizon',
    name: 'Verizon',
    category: 'carrier',
    phoneNumber: '1-800-922-0204',
    phoneNumberUS: '1-800-922-0204',
    phoneNumberUK: null,
    chatUrl: 'https://www.verizon.com/support/contact-us/',
    supportUrl: 'https://www.verizon.com/support/',
    hours: 'Mon-Sun 7am-11pm local time',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Say "representative" at the first prompt',
      'Press 0 twice to skip the menu',
      'Say "I want to cancel" to get transferred to retention (shorter wait)',
      'Use the My Verizon app chat for faster response',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Verizon supports wireless plans, billing, device setup, network issues, and home internet service.',
    logo: 'V',
  },
  {
    slug: 'att',
    name: 'AT&T',
    category: 'carrier',
    phoneNumber: '1-800-331-0500',
    phoneNumberUS: '1-800-331-0500',
    phoneNumberUK: null,
    chatUrl: 'https://www.att.com/support/contact-us/',
    supportUrl: 'https://www.att.com/support/',
    hours: 'Mon-Fri 7am-9pm CT, Sat 8am-9pm CT, Sun 8am-7pm CT',
    avgWaitTime: '15-30 min',
    tipsToReachHuman: [
      'Say "agent" or "representative" immediately',
      'Press 0 three times to bypass the menu',
      'Select "billing" for shorter wait times',
      'Call early morning or late evening for shorter waits',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'AT&T provides support for wireless service, internet, TV bundles, billing questions, and device troubleshooting.',
    logo: 'A',
  },
  {
    slug: 't-mobile',
    name: 'T-Mobile',
    category: 'carrier',
    phoneNumber: '1-800-937-8997',
    phoneNumberUS: '1-800-937-8997',
    phoneNumberUK: null,
    chatUrl: 'https://www.t-mobile.com/contact-us',
    supportUrl: 'https://www.t-mobile.com/support',
    hours: '24/7',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Dial 611 from your T-Mobile phone for faster access',
      'Say "representative" at the voice prompt',
      'Press 0 to skip automated options',
      'Use T-Mobile app messaging for quick help',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'T-Mobile (including former Sprint customers) provides support for wireless plans, billing, coverage, and device issues.',
    logo: 'T',
  },
  {
    slug: 'sprint-t-mobile',
    name: 'Sprint (now T-Mobile)',
    category: 'carrier',
    phoneNumber: '1-888-211-4727',
    phoneNumberUS: '1-888-211-4727',
    phoneNumberUK: null,
    chatUrl: 'https://www.t-mobile.com/contact-us',
    supportUrl: 'https://www.t-mobile.com/support/account/sprint-702-702',
    hours: '24/7',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Dial *2 from your Sprint phone',
      'Say "representative" when the automated system starts',
      'Sprint accounts are now managed by T-Mobile',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Sprint merged with T-Mobile. Former Sprint customers can still call the Sprint number for billing and account support.',
    logo: 'S',
  },
  {
    slug: 'spectrum-mobile',
    name: 'Spectrum Mobile',
    category: 'carrier',
    phoneNumber: '1-833-224-6603',
    phoneNumberUS: '1-833-224-6603',
    phoneNumberUK: null,
    chatUrl: 'https://www.spectrum.com/contact-us',
    supportUrl: 'https://www.spectrum.com/mobile',
    hours: '24/7',
    avgWaitTime: '10-15 min',
    tipsToReachHuman: [
      'Press 0 to skip the automated menu',
      'Say "cancel service" to reach a live agent fast',
      'Select "technical support" for device help',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Spectrum Mobile offers phone plans bundled with Spectrum Internet. Support covers billing, device setup, and network issues.',
    logo: 'S',
  },
  {
    slug: 'xfinity-mobile',
    name: 'Xfinity Mobile',
    category: 'carrier',
    phoneNumber: '1-888-936-4968',
    phoneNumberUS: '1-888-936-4968',
    phoneNumberUK: null,
    chatUrl: 'https://www.xfinity.com/support/contact-us',
    supportUrl: 'https://www.xfinity.com/mobile/support',
    hours: '24/7',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Say "agent" at the first prompt',
      'Press 0 to skip the menu',
      'Visit an Xfinity Store for in-person help',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Xfinity Mobile supports phone plans for Comcast internet customers, including device setup, billing, and data plans.',
    logo: 'X',
  },
  {
    slug: 'mint-mobile',
    name: 'Mint Mobile',
    category: 'carrier',
    phoneNumber: '1-800-683-7392',
    phoneNumberUS: '1-800-683-7392',
    phoneNumberUK: null,
    chatUrl: 'https://www.mintmobile.com/contact-us/',
    supportUrl: 'https://www.mintmobile.com/help/',
    hours: 'Mon-Sun 5am-7pm PT',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Press 0 to reach an agent immediately',
      'Use the Mint Mobile app chat for fastest help',
      'Say "speak to someone" at the prompt',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Mint Mobile is a budget-friendly carrier offering support for plan activation, SIM cards, and account management.',
    logo: 'M',
  },
  {
    slug: 'cricket-wireless',
    name: 'Cricket Wireless',
    category: 'carrier',
    phoneNumber: '1-800-274-2538',
    phoneNumberUS: '1-800-274-2538',
    phoneNumberUK: null,
    chatUrl: 'https://www.cricketwireless.com/support/contact-us',
    supportUrl: 'https://www.cricketwireless.com/support',
    hours: 'Mon-Sun 9am-9pm ET',
    avgWaitTime: '10-15 min',
    tipsToReachHuman: [
      'Press 0 at the main menu',
      'Say "representative" when prompted',
      'Dial 611 from your Cricket phone',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Cricket Wireless (owned by AT&T) supports prepaid phone plans, device activation, and billing questions.',
    logo: 'C',
  },
  {
    slug: 'visible',
    name: 'Visible',
    category: 'carrier',
    phoneNumber: null,
    phoneNumberUS: null,
    phoneNumberUK: null,
    chatUrl: 'https://www.visible.com/help/contact',
    supportUrl: 'https://www.visible.com/help',
    hours: 'Mon-Sun 8am-12am ET (chat only)',
    avgWaitTime: '5-10 min (chat)',
    tipsToReachHuman: [
      'Visible does not offer phone support — use chat or the app',
      'Open the Visible app and tap "Chat with us"',
      'Type "speak to agent" in the chatbot to bypass the bot',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Visible (by Verizon) is an online-only carrier. Support is available through chat and the app only — no phone number.',
    logo: 'V',
  },
  {
    slug: 'straight-talk',
    name: 'Straight Talk',
    category: 'carrier',
    phoneNumber: '1-877-430-2355',
    phoneNumberUS: '1-877-430-2355',
    phoneNumberUK: null,
    chatUrl: 'https://www.straighttalk.com/support/contact',
    supportUrl: 'https://www.straighttalk.com/support',
    hours: 'Mon-Sun 8am-11:45pm ET',
    avgWaitTime: '15-25 min',
    tipsToReachHuman: [
      'Press 0 three times to reach a live agent',
      'Say "agent" repeatedly if the system loops',
      'Have your phone number and PIN ready',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Straight Talk is a prepaid wireless carrier available at Walmart. Support covers plan activation, refills, and device setup.',
    logo: 'S',
  },

  // ─── Streaming (8) ────────────────────────────────────────────────────
  {
    slug: 'netflix',
    name: 'Netflix',
    category: 'streaming',
    phoneNumber: '1-844-505-2993',
    phoneNumberUS: '1-844-505-2993',
    phoneNumberUK: '0800-096-6379',
    chatUrl: 'https://help.netflix.com/en/contactus',
    supportUrl: 'https://help.netflix.com/',
    hours: '24/7',
    avgWaitTime: '3-8 min',
    tipsToReachHuman: [
      'Call and simply wait — Netflix connects you quickly',
      'Use the live chat on their website for instant help',
      'Log into your account first for faster verification',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Netflix support helps with account setup, billing, streaming problems, password resets, and device compatibility.',
    logo: 'N',
  },
  {
    slug: 'hulu',
    name: 'Hulu',
    category: 'streaming',
    phoneNumber: '1-888-631-4858',
    phoneNumberUS: '1-888-631-4858',
    phoneNumberUK: null,
    chatUrl: 'https://help.hulu.com/contact-us',
    supportUrl: 'https://help.hulu.com/',
    hours: '24/7',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Press 0 to skip the automated menu',
      'Say "speak to a person"',
      'Use live chat for faster response times',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Hulu support covers streaming issues, billing, account management, and help with Hulu + Live TV packages.',
    logo: 'H',
  },
  {
    slug: 'disney-plus',
    name: 'Disney+',
    category: 'streaming',
    phoneNumber: '1-888-905-7888',
    phoneNumberUS: '1-888-905-7888',
    phoneNumberUK: '0800-028-0778',
    chatUrl: 'https://help.disneyplus.com/contact-us',
    supportUrl: 'https://help.disneyplus.com/',
    hours: '24/7',
    avgWaitTime: '5-10 min',
    tipsToReachHuman: [
      'Press 0 at any time to reach an agent',
      'Say "representative" when prompted',
      'Use the chat feature for quick billing questions',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Disney+ support helps with account setup, streaming quality, billing, parental controls, and device compatibility.',
    logo: 'D',
  },
  {
    slug: 'amazon-prime-video',
    name: 'Amazon Prime Video',
    category: 'streaming',
    phoneNumber: '1-888-280-4331',
    phoneNumberUS: '1-888-280-4331',
    phoneNumberUK: '0800-279-7234',
    chatUrl: 'https://www.amazon.com/gp/help/contact-us',
    supportUrl: 'https://www.amazon.com/gp/help/customer/display.html',
    hours: '24/7',
    avgWaitTime: '3-10 min',
    tipsToReachHuman: [
      'Say "speak to a representative" at the first prompt',
      'Press 0 to skip the menu',
      'Request a callback through your Amazon account for zero wait',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Amazon Prime Video support covers streaming issues, Prime membership, billing, and Fire TV device problems.',
    logo: 'A',
  },
  {
    slug: 'hbo-max',
    name: 'HBO Max (Max)',
    category: 'streaming',
    phoneNumber: '1-855-442-6629',
    phoneNumberUS: '1-855-442-6629',
    phoneNumberUK: null,
    chatUrl: 'https://help.max.com/contact-us',
    supportUrl: 'https://help.max.com/',
    hours: '24/7',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Press 0 to reach a live agent',
      'Say "agent" when the automated system starts',
      'Use the chat feature on their help website',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Max (formerly HBO Max) support helps with streaming problems, billing, account management, and content questions.',
    logo: 'M',
  },
  {
    slug: 'youtube-tv',
    name: 'YouTube TV',
    category: 'streaming',
    phoneNumber: '1-833-998-1058',
    phoneNumberUS: '1-833-998-1058',
    phoneNumberUK: null,
    chatUrl: 'https://support.google.com/youtubetv/gethelp',
    supportUrl: 'https://support.google.com/youtubetv/',
    hours: '24/7',
    avgWaitTime: '5-10 min',
    tipsToReachHuman: [
      'Press 0 to skip the automated prompts',
      'Say "talk to a person" when prompted',
      'Use the callback feature in the YouTube TV app',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'YouTube TV support covers live TV streaming issues, DVR problems, channel lineups, and billing questions.',
    logo: 'Y',
  },
  {
    slug: 'paramount-plus',
    name: 'Paramount+',
    category: 'streaming',
    phoneNumber: '1-888-274-5343',
    phoneNumberUS: '1-888-274-5343',
    phoneNumberUK: null,
    chatUrl: 'https://help.paramountplus.com/s/contact',
    supportUrl: 'https://help.paramountplus.com/',
    hours: '24/7',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Press 0 to speak to an agent',
      'Say "customer service" when prompted',
      'Use the live chat for faster response',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Paramount+ support covers streaming issues, account management, billing, and help with the Paramount+ app.',
    logo: 'P',
  },
  {
    slug: 'peacock',
    name: 'Peacock',
    category: 'streaming',
    phoneNumber: '1-888-883-7277',
    phoneNumberUS: '1-888-883-7277',
    phoneNumberUK: null,
    chatUrl: 'https://www.peacocktv.com/help/contact-us',
    supportUrl: 'https://www.peacocktv.com/help',
    hours: 'Mon-Sun 9am-1am ET',
    avgWaitTime: '5-10 min',
    tipsToReachHuman: [
      'Press 0 at the menu to get a live agent',
      'Say "speak to someone" when prompted',
      'Use the help chat on peacocktv.com',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Peacock (by NBCUniversal) support covers streaming problems, subscription plans, billing, and content availability.',
    logo: 'P',
  },

  // ─── Social Media (6) ─────────────────────────────────────────────────
  {
    slug: 'facebook',
    name: 'Facebook (Meta)',
    category: 'social-media',
    phoneNumber: null,
    phoneNumberUS: null,
    phoneNumberUK: null,
    chatUrl: 'https://www.facebook.com/help/contact/540927709370269',
    supportUrl: 'https://www.facebook.com/help/',
    hours: '24/7 (online support only)',
    avgWaitTime: '1-3 days (email response)',
    tipsToReachHuman: [
      'Facebook does not offer phone support',
      'Go to Settings > Help & Support > Report a Problem',
      'For hacked accounts visit facebook.com/hacked',
      'Use the "Something Went Wrong" option in the Help Center',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Facebook help covers account recovery, privacy settings, reporting scams, and navigating the platform. No phone support available.',
    logo: 'F',
  },
  {
    slug: 'instagram',
    name: 'Instagram',
    category: 'social-media',
    phoneNumber: null,
    phoneNumberUS: null,
    phoneNumberUK: null,
    chatUrl: null,
    supportUrl: 'https://help.instagram.com/',
    hours: '24/7 (online support only)',
    avgWaitTime: '2-5 days (email response)',
    tipsToReachHuman: [
      'Instagram does not offer phone or chat support',
      'Go to Profile > Settings > Help > Report a Problem',
      'For hacked accounts use the "Get help logging in" link',
      'Report issues through the in-app help center',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Instagram support is online-only. Help covers account recovery, privacy settings, blocking users, and reporting problems.',
    logo: 'I',
  },
  {
    slug: 'whatsapp',
    name: 'WhatsApp',
    category: 'social-media',
    phoneNumber: null,
    phoneNumberUS: null,
    phoneNumberUK: null,
    chatUrl: null,
    supportUrl: 'https://faq.whatsapp.com/',
    hours: '24/7 (online support only)',
    avgWaitTime: '1-3 days (email response)',
    tipsToReachHuman: [
      'WhatsApp does not offer phone support',
      'Email support@whatsapp.com for help',
      'Go to Settings > Help > Contact Us in the app',
      'For account issues include your phone number in the email',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'WhatsApp support is email-only. Covers messaging issues, account verification, privacy, and group chat help.',
    logo: 'W',
  },
  {
    slug: 'youtube',
    name: 'YouTube',
    category: 'social-media',
    phoneNumber: null,
    phoneNumberUS: null,
    phoneNumberUK: null,
    chatUrl: 'https://support.google.com/youtube/gethelp',
    supportUrl: 'https://support.google.com/youtube/',
    hours: '24/7 (online support)',
    avgWaitTime: '1-2 days (email), instant (chat for Premium)',
    tipsToReachHuman: [
      'YouTube Premium members can access live chat support',
      'Use the "Get support" button in the YouTube Help Center',
      'Post in the YouTube Community Help Forum for peer support',
      'For account issues contact Google support directly',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'YouTube support covers video playback, account issues, privacy settings, and YouTube Premium subscription help.',
    logo: 'Y',
  },
  {
    slug: 'twitter-x',
    name: 'Twitter / X',
    category: 'social-media',
    phoneNumber: null,
    phoneNumberUS: null,
    phoneNumberUK: null,
    chatUrl: null,
    supportUrl: 'https://help.x.com/',
    hours: '24/7 (online support only)',
    avgWaitTime: '3-7 days (email response)',
    tipsToReachHuman: [
      'Twitter/X does not offer phone or chat support',
      'Go to Settings > Help Center > Contact Us',
      'For hacked accounts visit help.x.com/en/forms/account-access',
      'Be persistent — response times can be slow',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Twitter/X support is online-only. Help covers account recovery, privacy, blocking, and reporting content.',
    logo: 'X',
  },
  {
    slug: 'tiktok',
    name: 'TikTok',
    category: 'social-media',
    phoneNumber: null,
    phoneNumberUS: null,
    phoneNumberUK: null,
    chatUrl: null,
    supportUrl: 'https://support.tiktok.com/',
    hours: '24/7 (online support only)',
    avgWaitTime: '2-5 days (email response)',
    tipsToReachHuman: [
      'TikTok does not offer phone support',
      'Go to Profile > Settings > Report a Problem',
      'Email feedback@tiktok.com for account issues',
      'Use the in-app "Report a Problem" feature',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'TikTok support is online-only. Covers account issues, privacy settings, content reporting, and parental controls.',
    logo: 'T',
  },

  // ─── Email (4) ────────────────────────────────────────────────────────
  {
    slug: 'gmail-google',
    name: 'Gmail / Google',
    category: 'email',
    phoneNumber: '1-844-245-2553',
    phoneNumberUS: '1-844-245-2553',
    phoneNumberUK: '0800-328-8238',
    chatUrl: 'https://support.google.com/mail/gethelp',
    supportUrl: 'https://support.google.com/mail/',
    hours: '24/7',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Say "speak to a representative" at the prompt',
      'Press 0 to skip the menu',
      'Sign into your Google account first for faster verification',
      'Use the "Get help" button in Gmail settings for chat support',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Google support helps with Gmail login issues, password recovery, spam problems, storage, and Google account security.',
    logo: 'G',
  },
  {
    slug: 'yahoo-mail',
    name: 'Yahoo Mail',
    category: 'email',
    phoneNumber: '1-800-305-7664',
    phoneNumberUS: '1-800-305-7664',
    phoneNumberUK: '0800-073-1073',
    chatUrl: 'https://help.yahoo.com/contact',
    supportUrl: 'https://help.yahoo.com/',
    hours: '24/7',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 at the menu to reach a live agent',
      'Say "operator" when the automated system starts',
      'Be aware of scam numbers — only call the official Yahoo number',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Yahoo Mail support covers email login problems, password resets, spam filtering, and account recovery.',
    logo: 'Y',
  },
  {
    slug: 'outlook-microsoft',
    name: 'Outlook / Microsoft',
    category: 'email',
    phoneNumber: '1-800-642-7676',
    phoneNumberUS: '1-800-642-7676',
    phoneNumberUK: '0800-026-0329',
    chatUrl: 'https://support.microsoft.com/contactus',
    supportUrl: 'https://support.microsoft.com/en-us/outlook',
    hours: 'Mon-Fri 6am-6pm PT, Sat-Sun 6am-3pm PT',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Say "Outlook" then "speak to a person"',
      'Press 0 to skip the automated options',
      'Use the virtual agent on support.microsoft.com and request a callback',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Microsoft supports Outlook.com, Hotmail, and Live email accounts with login help, password resets, and email troubleshooting.',
    logo: 'O',
  },
  {
    slug: 'aol',
    name: 'AOL',
    category: 'email',
    phoneNumber: '1-800-827-6364',
    phoneNumberUS: '1-800-827-6364',
    phoneNumberUK: null,
    chatUrl: 'https://help.aol.com/contact',
    supportUrl: 'https://help.aol.com/',
    hours: 'Mon-Fri 8am-12am ET',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 to skip the automated menu',
      'Say "representative" when prompted',
      'AOL is now owned by Yahoo — some support may redirect there',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'AOL Mail support helps with email login, password recovery, spam issues, and account security. AOL is now part of Yahoo.',
    logo: 'A',
  },

  // ─── Banking (8) ──────────────────────────────────────────────────────
  {
    slug: 'bank-of-america',
    name: 'Bank of America',
    category: 'banking',
    phoneNumber: '1-800-432-1000',
    phoneNumberUS: '1-800-432-1000',
    phoneNumberUK: null,
    chatUrl: 'https://www.bankofamerica.com/online-banking/sign-in/',
    supportUrl: 'https://www.bankofamerica.com/customer-service/',
    hours: '24/7 (automated), Mon-Fri 7am-10pm ET (live agent)',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 at any point to reach an agent',
      'Say "representative" at the voice prompt',
      'Have your account number or debit card ready',
      'Select "report fraud" for immediate live agent access',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Bank of America support covers checking, savings, credit cards, online banking, fraud reporting, and mortgage questions.',
    logo: 'B',
  },
  {
    slug: 'chase',
    name: 'Chase',
    category: 'banking',
    phoneNumber: '1-800-935-9935',
    phoneNumberUS: '1-800-935-9935',
    phoneNumberUK: null,
    chatUrl: 'https://www.chase.com/digital/customer-service',
    supportUrl: 'https://www.chase.com/digital/customer-service',
    hours: '24/7',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Press 0 twice to reach an agent',
      'Say "speak to a person" at the prompt',
      'For credit cards call 1-800-432-3117 instead',
      'Use the Chase Mobile app secure messaging for quick help',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Chase supports checking, savings, credit cards, auto loans, mortgage, and investment accounts.',
    logo: 'C',
  },
  {
    slug: 'wells-fargo',
    name: 'Wells Fargo',
    category: 'banking',
    phoneNumber: '1-800-869-3557',
    phoneNumberUS: '1-800-869-3557',
    phoneNumberUK: null,
    chatUrl: 'https://www.wellsfargo.com/help/contact-us/',
    supportUrl: 'https://www.wellsfargo.com/help/',
    hours: '24/7',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 to skip the automated menu',
      'Say "agent" when prompted',
      'Have your account number or Social Security number ready',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Wells Fargo provides support for checking, savings, credit cards, mortgages, online banking, and fraud concerns.',
    logo: 'W',
  },
  {
    slug: 'capital-one',
    name: 'Capital One',
    category: 'banking',
    phoneNumber: '1-877-383-4802',
    phoneNumberUS: '1-877-383-4802',
    phoneNumberUK: '0800-952-5267',
    chatUrl: 'https://www.capitalone.com/support-center/contact-us',
    supportUrl: 'https://www.capitalone.com/support-center/',
    hours: '24/7',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Press 0 at the main menu',
      'Say "representative" when prompted',
      'For credit cards call 1-800-227-4825',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Capital One supports credit cards, checking, savings, auto loans, and 360 online banking accounts.',
    logo: 'C',
  },
  {
    slug: 'citi',
    name: 'Citibank',
    category: 'banking',
    phoneNumber: '1-800-374-9700',
    phoneNumberUS: '1-800-374-9700',
    phoneNumberUK: '0800-005-056',
    chatUrl: 'https://www.citi.com/customer-service',
    supportUrl: 'https://www.citi.com/customer-service',
    hours: '24/7',
    avgWaitTime: '10-15 min',
    tipsToReachHuman: [
      'Press 0 twice to reach an agent',
      'Say "customer service" when prompted',
      'Have your account or card number ready',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Citibank support covers credit cards, banking accounts, wire transfers, and fraud reporting.',
    logo: 'C',
  },
  {
    slug: 'usaa',
    name: 'USAA',
    category: 'banking',
    phoneNumber: '1-800-531-8722',
    phoneNumberUS: '1-800-531-8722',
    phoneNumberUK: null,
    chatUrl: 'https://www.usaa.com/help',
    supportUrl: 'https://www.usaa.com/help',
    hours: '24/7',
    avgWaitTime: '5-10 min',
    tipsToReachHuman: [
      'Press 0 to reach an agent immediately',
      'Say "speak to a representative"',
      'USAA is known for excellent wait times',
      'Have your USAA member number ready',
    ],
    seniorSupport: true,
    seniorLine: null,
    description: 'USAA provides banking, insurance, and financial services exclusively for military members, veterans, and their families.',
    logo: 'U',
  },
  {
    slug: 'american-express',
    name: 'American Express',
    category: 'banking',
    phoneNumber: '1-800-528-4800',
    phoneNumberUS: '1-800-528-4800',
    phoneNumberUK: '0800-917-8047',
    chatUrl: 'https://www.americanexpress.com/us/customer-service/contact-us.html',
    supportUrl: 'https://www.americanexpress.com/us/customer-service/',
    hours: '24/7',
    avgWaitTime: '3-10 min',
    tipsToReachHuman: [
      'Press 0 to reach an agent',
      'Say "representative" at the prompt',
      'Amex is known for quick connections to live agents',
      'Have your card number ready for faster service',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'American Express provides credit card support including billing, disputes, rewards, travel benefits, and fraud protection.',
    logo: 'A',
  },
  {
    slug: 'paypal',
    name: 'PayPal',
    category: 'banking',
    phoneNumber: '1-888-221-1161',
    phoneNumberUS: '1-888-221-1161',
    phoneNumberUK: '0800-358-7911',
    chatUrl: 'https://www.paypal.com/us/smarthelp/contact-us',
    supportUrl: 'https://www.paypal.com/us/smarthelp/home',
    hours: 'Mon-Sun 6am-6pm PT',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 to skip the automated menu',
      'Say "representative" at the voice prompt',
      'Log into PayPal first and use the "Call Us" button for a one-time PIN',
      'Use the Message Center in your PayPal account for quick questions',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'PayPal support helps with payments, money transfers, disputes, account security, and connecting bank accounts.',
    logo: 'P',
  },

  // ─── Shopping (5) ─────────────────────────────────────────────────────
  {
    slug: 'amazon',
    name: 'Amazon',
    category: 'shopping',
    phoneNumber: '1-888-280-4331',
    phoneNumberUS: '1-888-280-4331',
    phoneNumberUK: '0800-279-7234',
    chatUrl: 'https://www.amazon.com/gp/help/contact-us',
    supportUrl: 'https://www.amazon.com/gp/help/customer/display.html',
    hours: '24/7',
    avgWaitTime: '3-5 min',
    tipsToReachHuman: [
      'Say "speak to a representative" at the first prompt',
      'Request a callback through your Amazon account for zero wait',
      'Press 0 to skip automated options',
      'The callback feature is the fastest way to reach a human',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Amazon support covers orders, returns, refunds, Prime membership, Kindle, Alexa, and account security.',
    logo: 'A',
  },
  {
    slug: 'walmart',
    name: 'Walmart',
    category: 'shopping',
    phoneNumber: '1-800-925-6278',
    phoneNumberUS: '1-800-925-6278',
    phoneNumberUK: null,
    chatUrl: 'https://www.walmart.com/help',
    supportUrl: 'https://www.walmart.com/help',
    hours: 'Mon-Sun 8am-11pm ET',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 to skip the menu',
      'Say "customer service" when prompted',
      'Select "online orders" for faster routing',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Walmart support covers online orders, returns, Walmart+ membership, pharmacy, and store-related questions.',
    logo: 'W',
  },
  {
    slug: 'target',
    name: 'Target',
    category: 'shopping',
    phoneNumber: '1-800-440-0680',
    phoneNumberUS: '1-800-440-0680',
    phoneNumberUK: null,
    chatUrl: 'https://www.target.com/co-contactUs',
    supportUrl: 'https://help.target.com/',
    hours: 'Mon-Sun 7am-11pm CT',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Press 0 at the menu to reach an agent',
      'Say "representative" when prompted',
      'Have your order number ready for online order questions',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Target support covers online orders, returns, Target Circle rewards, RedCard, and store-related questions.',
    logo: 'T',
  },
  {
    slug: 'best-buy',
    name: 'Best Buy',
    category: 'shopping',
    phoneNumber: '1-888-237-8289',
    phoneNumberUS: '1-888-237-8289',
    phoneNumberUK: null,
    chatUrl: 'https://www.bestbuy.com/support',
    supportUrl: 'https://www.bestbuy.com/support',
    hours: 'Mon-Sun 8am-11pm ET',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 to skip the menu',
      'Say "representative" when prompted',
      'Select "Geek Squad" for tech support help',
      'Visit a store for free in-person tech help',
    ],
    seniorSupport: true,
    seniorLine: null,
    description: 'Best Buy and Geek Squad support covers electronics purchases, returns, tech support, computer setup, and device repair.',
    logo: 'B',
  },
  {
    slug: 'ebay',
    name: 'eBay',
    category: 'shopping',
    phoneNumber: '1-866-540-3229',
    phoneNumberUS: '1-866-540-3229',
    phoneNumberUK: '0345-355-3229',
    chatUrl: 'https://www.ebay.com/help/home',
    supportUrl: 'https://www.ebay.com/help/home',
    hours: 'Mon-Sun 6am-9pm PT',
    avgWaitTime: '15-25 min',
    tipsToReachHuman: [
      'Press 0 twice to reach an agent',
      'Say "agent" when the automated system starts',
      'Log into your eBay account and use "Contact Us" for faster routing',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'eBay support covers buying, selling, auctions, returns, PayPal payments, and account security.',
    logo: 'E',
  },

  // ─── Smart Home (5) ───────────────────────────────────────────────────
  {
    slug: 'amazon-alexa',
    name: 'Amazon Alexa',
    category: 'smart-home',
    phoneNumber: '1-877-375-9365',
    phoneNumberUS: '1-877-375-9365',
    phoneNumberUK: '0800-279-7234',
    chatUrl: 'https://www.amazon.com/gp/help/contact-us',
    supportUrl: 'https://www.amazon.com/gp/help/customer/display.html?nodeId=GX7NJR2TWMFHM56B',
    hours: '24/7',
    avgWaitTime: '3-8 min',
    tipsToReachHuman: [
      'Say "speak to a representative" at the first prompt',
      'Request a callback through your Amazon account',
      'Say "Alexa, help" to your Echo device for basic troubleshooting',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Amazon Alexa support covers Echo devices, smart home setup, voice commands, routines, and connected device issues.',
    logo: 'A',
  },
  {
    slug: 'google-home',
    name: 'Google Home / Nest Hub',
    category: 'smart-home',
    phoneNumber: '1-855-971-9121',
    phoneNumberUS: '1-855-971-9121',
    phoneNumberUK: '0800-328-8238',
    chatUrl: 'https://support.google.com/googlenest/gethelp',
    supportUrl: 'https://support.google.com/googlenest/',
    hours: '24/7',
    avgWaitTime: '5-10 min',
    tipsToReachHuman: [
      'Press 0 to reach an agent',
      'Say "speak to a person" when prompted',
      'Use the Google Home app to request a callback',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Google Home support helps with Nest speakers, displays, WiFi, thermostats, cameras, and smart home automation.',
    logo: 'G',
  },
  {
    slug: 'apple-homekit',
    name: 'Apple HomeKit',
    category: 'smart-home',
    phoneNumber: '1-800-275-2273',
    phoneNumberUS: '1-800-275-2273',
    phoneNumberUK: '0800-048-0408',
    chatUrl: 'https://support.apple.com/contact',
    supportUrl: 'https://support.apple.com/home-app',
    hours: 'Mon-Sun 8am-8pm local time',
    avgWaitTime: '5-10 min',
    tipsToReachHuman: [
      'Say "HomeKit" or "Home app" when prompted',
      'Press 0 to skip automated options',
      'Select "other Apple products" from the menu',
    ],
    seniorSupport: true,
    seniorLine: '1-800-275-2273',
    description: 'Apple HomeKit support covers the Home app, smart home accessories, automation, and Apple TV as a home hub.',
    logo: '🍎',
  },
  {
    slug: 'ring',
    name: 'Ring',
    category: 'smart-home',
    phoneNumber: '1-800-656-1918',
    phoneNumberUS: '1-800-656-1918',
    phoneNumberUK: '0800-740-8458',
    chatUrl: 'https://ring.com/contact',
    supportUrl: 'https://support.ring.com/',
    hours: '24/7',
    avgWaitTime: '5-10 min',
    tipsToReachHuman: [
      'Press 0 to reach an agent immediately',
      'Say "speak to someone" when prompted',
      'Use the Ring app to request a callback',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Ring support covers video doorbells, security cameras, alarm systems, and the Ring app.',
    logo: 'R',
  },
  {
    slug: 'nest',
    name: 'Google Nest',
    category: 'smart-home',
    phoneNumber: '1-855-469-6378',
    phoneNumberUS: '1-855-469-6378',
    phoneNumberUK: '0800-328-8238',
    chatUrl: 'https://support.google.com/googlenest/gethelp',
    supportUrl: 'https://support.google.com/googlenest/',
    hours: '24/7',
    avgWaitTime: '5-10 min',
    tipsToReachHuman: [
      'Press 0 to skip the menu',
      'Say "representative" when prompted',
      'Specify your product (thermostat, camera, etc.) for faster routing',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Google Nest support covers Nest thermostats, cameras, doorbells, smoke detectors, and Nest WiFi.',
    logo: 'N',
  },

  // ─── Computer / Software (6) ──────────────────────────────────────────
  {
    slug: 'microsoft-windows',
    name: 'Microsoft Windows',
    category: 'computer',
    phoneNumber: '1-800-642-7676',
    phoneNumberUS: '1-800-642-7676',
    phoneNumberUK: '0800-026-0329',
    chatUrl: 'https://support.microsoft.com/contactus',
    supportUrl: 'https://support.microsoft.com/en-us/windows',
    hours: 'Mon-Fri 6am-6pm PT, Sat-Sun 6am-3pm PT',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Say "Windows" then "speak to a person"',
      'Press 0 to skip the automated system',
      'Use the "Get Help" app built into Windows 10/11',
      'Request a callback through support.microsoft.com',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Microsoft Windows support covers updates, security, performance, printer setup, and general PC troubleshooting.',
    logo: 'W',
  },
  {
    slug: 'apple-mac',
    name: 'Apple Mac',
    category: 'computer',
    phoneNumber: '1-800-275-2273',
    phoneNumberUS: '1-800-275-2273',
    phoneNumberUK: '0800-048-0408',
    chatUrl: 'https://support.apple.com/contact',
    supportUrl: 'https://support.apple.com/mac',
    hours: 'Mon-Sun 8am-8pm local time',
    avgWaitTime: '5-10 min',
    tipsToReachHuman: [
      'Say "Mac" when prompted for product type',
      'Press 0 to skip automated options',
      'Have your Mac serial number ready (Apple menu > About This Mac)',
    ],
    seniorSupport: true,
    seniorLine: '1-800-275-2273',
    description: 'Apple Mac support covers macOS, hardware issues, iCloud, Time Machine backups, and Apple software.',
    logo: '🍎',
  },
  {
    slug: 'hp',
    name: 'HP (Hewlett-Packard)',
    category: 'computer',
    phoneNumber: '1-800-474-6836',
    phoneNumberUS: '1-800-474-6836',
    phoneNumberUK: '0207-660-0596',
    chatUrl: 'https://support.hp.com/us-en/contact-hp',
    supportUrl: 'https://support.hp.com/',
    hours: 'Mon-Fri 7am-7pm CT',
    avgWaitTime: '15-25 min',
    tipsToReachHuman: [
      'Press 0 to skip the menu',
      'Say "agent" at the voice prompt',
      'Have your HP product number ready (on the sticker under your laptop)',
      'Use HP Virtual Agent online for quick troubleshooting',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'HP supports laptops, desktops, printers, and monitors with help for setup, drivers, hardware issues, and warranty claims.',
    logo: 'H',
  },
  {
    slug: 'dell',
    name: 'Dell',
    category: 'computer',
    phoneNumber: '1-800-624-9897',
    phoneNumberUS: '1-800-624-9897',
    phoneNumberUK: '0800-028-2660',
    chatUrl: 'https://www.dell.com/support/home/en-us',
    supportUrl: 'https://www.dell.com/support/',
    hours: 'Mon-Fri 8am-8pm ET',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 to skip the automated menu',
      'Say "technical support" for computer help',
      'Have your Dell Service Tag ready (on the sticker on your computer)',
      'Enter your Service Tag on dell.com/support for faster help',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Dell supports laptops, desktops, and monitors with help for setup, drivers, hardware repairs, and warranty service.',
    logo: 'D',
  },
  {
    slug: 'lenovo',
    name: 'Lenovo',
    category: 'computer',
    phoneNumber: '1-855-253-6686',
    phoneNumberUS: '1-855-253-6686',
    phoneNumberUK: '0370-190-5000',
    chatUrl: 'https://support.lenovo.com/contactus',
    supportUrl: 'https://support.lenovo.com/',
    hours: 'Mon-Fri 9am-9pm ET',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 to skip the automated menu',
      'Say "representative" when prompted',
      'Have your Lenovo serial number ready',
      'Select "ThinkPad" or "IdeaPad" for proper routing',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Lenovo supports ThinkPad, IdeaPad, and Yoga laptops plus desktops with setup help, driver issues, and warranty claims.',
    logo: 'L',
  },
  {
    slug: 'norton-antivirus',
    name: 'Norton Antivirus',
    category: 'computer',
    phoneNumber: '1-844-488-4540',
    phoneNumberUS: '1-844-488-4540',
    phoneNumberUK: '0800-048-8615',
    chatUrl: 'https://support.norton.com/sp/en/us/home/current/contact',
    supportUrl: 'https://support.norton.com/',
    hours: '24/7',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Press 0 to skip the menu',
      'Say "speak to a person" at the prompt',
      'Have your Norton account email ready',
      'Be cautious of fake Norton support numbers in search results',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Norton Antivirus support covers virus removal, subscription management, VPN, password manager, and security alerts.',
    logo: 'N',
  },

  // ─── Internet Providers (8) ───────────────────────────────────────────
  {
    slug: 'comcast-xfinity',
    name: 'Comcast / Xfinity',
    category: 'internet-provider',
    phoneNumber: '1-800-934-6489',
    phoneNumberUS: '1-800-934-6489',
    phoneNumberUK: null,
    chatUrl: 'https://www.xfinity.com/support/contact-us',
    supportUrl: 'https://www.xfinity.com/support',
    hours: '24/7',
    avgWaitTime: '15-30 min',
    tipsToReachHuman: [
      'Say "agent" or "representative" immediately',
      'Press 0 three times to skip the menu',
      'Say "cancel service" to get to retention (faster connection)',
      'Visit an Xfinity Store for in-person help',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Xfinity support covers internet, WiFi, TV, billing, outages, and equipment (modem/router) issues.',
    logo: 'X',
  },
  {
    slug: 'spectrum-internet',
    name: 'Spectrum Internet',
    category: 'internet-provider',
    phoneNumber: '1-833-267-6094',
    phoneNumberUS: '1-833-267-6094',
    phoneNumberUK: null,
    chatUrl: 'https://www.spectrum.com/contact-us',
    supportUrl: 'https://www.spectrum.com/support',
    hours: '24/7',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 to skip the menu',
      'Say "representative" at the voice prompt',
      'Select "technical support" for internet issues',
      'Visit a Spectrum Store for in-person help',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Spectrum supports home internet, WiFi, TV, phone service, billing, and equipment troubleshooting.',
    logo: 'S',
  },
  {
    slug: 'att-internet',
    name: 'AT&T Internet',
    category: 'internet-provider',
    phoneNumber: '1-800-288-2020',
    phoneNumberUS: '1-800-288-2020',
    phoneNumberUK: null,
    chatUrl: 'https://www.att.com/support/contact-us/',
    supportUrl: 'https://www.att.com/support/internet/',
    hours: '24/7',
    avgWaitTime: '15-25 min',
    tipsToReachHuman: [
      'Say "agent" at the first prompt',
      'Press 0 three times to bypass the menu',
      'Select "technical support" then "internet"',
      'Call early morning for shorter wait times',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'AT&T Internet support covers fiber, DSL, WiFi, billing, outages, and modem/router troubleshooting.',
    logo: 'A',
  },
  {
    slug: 'verizon-fios',
    name: 'Verizon Fios',
    category: 'internet-provider',
    phoneNumber: '1-800-837-4966',
    phoneNumberUS: '1-800-837-4966',
    phoneNumberUK: null,
    chatUrl: 'https://www.verizon.com/support/contact-us/',
    supportUrl: 'https://www.verizon.com/support/residential/internet',
    hours: '24/7',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Say "representative" at the first prompt',
      'Press 0 twice to skip the menu',
      'Select "technical support" for internet issues',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Verizon Fios support covers fiber internet, TV, phone bundles, WiFi, billing, and equipment issues.',
    logo: 'V',
  },
  {
    slug: 'centurylink',
    name: 'CenturyLink (Lumen)',
    category: 'internet-provider',
    phoneNumber: '1-800-244-1111',
    phoneNumberUS: '1-800-244-1111',
    phoneNumberUK: null,
    chatUrl: 'https://www.centurylink.com/home/help/contact.html',
    supportUrl: 'https://www.centurylink.com/home/help.html',
    hours: 'Mon-Fri 8am-6pm local time',
    avgWaitTime: '15-25 min',
    tipsToReachHuman: [
      'Press 0 to skip the automated system',
      'Say "representative" when prompted',
      'Select "technical support" for internet help',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'CenturyLink (now Lumen) provides DSL and fiber internet support including billing, outages, and modem setup.',
    logo: 'C',
  },
  {
    slug: 'cox',
    name: 'Cox Communications',
    category: 'internet-provider',
    phoneNumber: '1-800-234-3993',
    phoneNumberUS: '1-800-234-3993',
    phoneNumberUK: null,
    chatUrl: 'https://www.cox.com/residential/support/contact-us.html',
    supportUrl: 'https://www.cox.com/residential/support.html',
    hours: '24/7',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 twice to reach an agent',
      'Say "technical support" for internet help',
      'Use the Cox app for outage reports and quick troubleshooting',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Cox Communications supports internet, TV, phone bundles, WiFi, billing, outage reports, and equipment issues.',
    logo: 'C',
  },
  {
    slug: 'frontier',
    name: 'Frontier Communications',
    category: 'internet-provider',
    phoneNumber: '1-800-921-8101',
    phoneNumberUS: '1-800-921-8101',
    phoneNumberUK: null,
    chatUrl: 'https://frontier.com/helpcenter/contact-us',
    supportUrl: 'https://frontier.com/helpcenter',
    hours: 'Mon-Fri 8am-7pm ET',
    avgWaitTime: '15-30 min',
    tipsToReachHuman: [
      'Press 0 to skip the menu',
      'Say "agent" when prompted',
      'Select "repair" for the fastest connection to tech support',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Frontier supports fiber and DSL internet, phone service, billing, outages, and equipment troubleshooting.',
    logo: 'F',
  },
  {
    slug: 'google-fiber',
    name: 'Google Fiber',
    category: 'internet-provider',
    phoneNumber: '1-866-777-7550',
    phoneNumberUS: '1-866-777-7550',
    phoneNumberUK: null,
    chatUrl: 'https://support.google.com/fiber/gethelp',
    supportUrl: 'https://support.google.com/fiber/',
    hours: '24/7',
    avgWaitTime: '3-10 min',
    tipsToReachHuman: [
      'Press 0 to reach an agent',
      'Say "technical support" for internet help',
      'Google Fiber is known for short wait times',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Google Fiber provides gigabit internet support including WiFi, billing, installation, and network troubleshooting.',
    logo: 'G',
  },

  // ─── Government / Utilities (5) ───────────────────────────────────────
  {
    slug: 'medicare',
    name: 'Medicare',
    category: 'government',
    phoneNumber: '1-800-633-4227',
    phoneNumberUS: '1-800-633-4227',
    phoneNumberUK: null,
    chatUrl: null,
    supportUrl: 'https://www.medicare.gov/talk-to-someone',
    hours: '24/7',
    avgWaitTime: '15-30 min',
    tipsToReachHuman: [
      'Press 0 to reach an agent',
      'Say "agent" or "representative" when prompted',
      'Call early morning (before 10am ET) for shorter waits',
      'Have your Medicare number and date of birth ready',
      'TTY users: 1-877-486-2048',
    ],
    seniorSupport: true,
    seniorLine: '1-800-633-4227',
    description: 'Medicare support covers enrollment, benefits, claims, prescription drug plans (Part D), Medicare Advantage, and billing questions.',
    logo: 'M',
  },
  {
    slug: 'social-security',
    name: 'Social Security Administration',
    category: 'government',
    phoneNumber: '1-800-772-1213',
    phoneNumberUS: '1-800-772-1213',
    phoneNumberUK: null,
    chatUrl: null,
    supportUrl: 'https://www.ssa.gov/contact',
    hours: 'Mon-Fri 8am-7pm local time',
    avgWaitTime: '20-45 min',
    tipsToReachHuman: [
      'Press 1 for English, then wait through prompts to reach an agent',
      'Do NOT press any number — just wait for the agent',
      'Call at 8am sharp for shortest waits',
      'Wednesday and Thursday typically have shorter waits',
      'Have your Social Security number ready',
    ],
    seniorSupport: true,
    seniorLine: '1-800-772-1213',
    description: 'Social Security support covers retirement benefits, disability, survivors benefits, Medicare enrollment, and replacement cards.',
    logo: 'S',
  },
  {
    slug: 'irs',
    name: 'IRS (Internal Revenue Service)',
    category: 'government',
    phoneNumber: '1-800-829-1040',
    phoneNumberUS: '1-800-829-1040',
    phoneNumberUK: null,
    chatUrl: null,
    supportUrl: 'https://www.irs.gov/help/telephone-assistance',
    hours: 'Mon-Fri 7am-7pm local time',
    avgWaitTime: '30-60 min',
    tipsToReachHuman: [
      'Press 1 for English, then 2, then 1, then 3, then 2 to reach an agent',
      'Call at 7am sharp for shortest waits',
      'Monday and Tuesday are the busiest days — try Wednesday-Friday',
      'Have your Social Security number and last tax return ready',
      'For refund status call 1-800-829-4477 instead',
    ],
    seniorSupport: true,
    seniorLine: null,
    description: 'IRS support covers tax filing, refunds, payments, tax forms, identity verification, and tax account questions.',
    logo: 'I',
  },
  {
    slug: 'usps',
    name: 'USPS (US Postal Service)',
    category: 'government',
    phoneNumber: '1-800-275-8777',
    phoneNumberUS: '1-800-275-8777',
    phoneNumberUK: null,
    chatUrl: 'https://www.usps.com/help/contact-us.htm',
    supportUrl: 'https://www.usps.com/help/',
    hours: 'Mon-Fri 8am-8:30pm ET, Sat 8am-6pm ET',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Say "agent" or press 0 at the first menu',
      'Say "track a package" and then ask for agent for package issues',
      'Use USPS.com tracking for quickest package updates',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'USPS support covers package tracking, mail delivery, address changes, hold mail, and passport applications.',
    logo: 'U',
  },
  {
    slug: 'dmv',
    name: 'DMV (Department of Motor Vehicles)',
    category: 'government',
    phoneNumber: null,
    phoneNumberUS: null,
    phoneNumberUK: null,
    chatUrl: null,
    supportUrl: 'https://www.usa.gov/motor-vehicle-services',
    hours: 'Varies by state — check your state DMV website',
    avgWaitTime: 'Varies by state',
    tipsToReachHuman: [
      'DMV phone numbers vary by state — search "[your state] DMV phone number"',
      'Many states now offer online appointment scheduling',
      'Try visiting during mid-week (Tue-Thu) for shorter lines',
      'Real ID appointments may need to be booked weeks in advance',
      'Check if your task can be done online at your state DMV website',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'DMV services vary by state. They handle driver licenses, vehicle registration, Real ID, and title transfers. Phone numbers differ by state.',
    logo: 'D',
  },

  // ─── Security (5) ─────────────────────────────────────────────────────
  {
    slug: 'norton-security',
    name: 'Norton Security',
    category: 'security',
    phoneNumber: '1-844-488-4540',
    phoneNumberUS: '1-844-488-4540',
    phoneNumberUK: '0800-048-8615',
    chatUrl: 'https://support.norton.com/sp/en/us/home/current/contact',
    supportUrl: 'https://support.norton.com/',
    hours: '24/7',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Press 0 to skip the menu',
      'Say "speak to a person" at the prompt',
      'Have your Norton account email ready',
      'WARNING: Be cautious of fake Norton numbers in Google results',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Norton Security provides antivirus protection, identity theft monitoring, VPN, and password manager support.',
    logo: 'N',
  },
  {
    slug: 'mcafee',
    name: 'McAfee',
    category: 'security',
    phoneNumber: '1-866-622-3911',
    phoneNumberUS: '1-866-622-3911',
    phoneNumberUK: '0800-015-3942',
    chatUrl: 'https://www.mcafee.com/support/',
    supportUrl: 'https://www.mcafee.com/support/',
    hours: '24/7',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 to reach an agent',
      'Say "representative" when prompted',
      'WARNING: Many fake McAfee support scam numbers exist — only call this official number',
      'Have your McAfee account email ready',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'McAfee supports antivirus, identity protection, VPN, and device security across computers and phones.',
    logo: 'M',
  },
  {
    slug: 'bitdefender',
    name: 'Bitdefender',
    category: 'security',
    phoneNumber: '1-954-920-3660',
    phoneNumberUS: '1-954-920-3660',
    phoneNumberUK: null,
    chatUrl: 'https://www.bitdefender.com/consumer/support/',
    supportUrl: 'https://www.bitdefender.com/consumer/support/',
    hours: '24/7',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Press 0 to reach an agent',
      'Use the live chat on their website for faster help',
      'Have your Bitdefender subscription email ready',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Bitdefender provides antivirus, internet security, and VPN support for computers and mobile devices.',
    logo: 'B',
  },
  {
    slug: 'lifelock',
    name: 'LifeLock',
    category: 'security',
    phoneNumber: '1-800-543-3562',
    phoneNumberUS: '1-800-543-3562',
    phoneNumberUK: null,
    chatUrl: 'https://www.lifelock.com/contact-us',
    supportUrl: 'https://www.lifelock.com/support',
    hours: 'Mon-Fri 6am-10pm PT, Sat 7am-7pm PT',
    avgWaitTime: '5-10 min',
    tipsToReachHuman: [
      'Press 0 to reach an agent',
      'Say "identity theft alert" for immediate priority routing',
      'Have your member number ready',
    ],
    seniorSupport: true,
    seniorLine: null,
    description: 'LifeLock (by Norton) provides identity theft protection, credit monitoring, and fraud alert support.',
    logo: 'L',
  },
  {
    slug: 'credit-bureaus',
    name: 'Credit Bureaus (Equifax / Experian / TransUnion)',
    category: 'security',
    phoneNumber: '1-888-397-3742',
    phoneNumberUS: '1-888-397-3742',
    phoneNumberUK: null,
    chatUrl: null,
    supportUrl: 'https://www.annualcreditreport.com/',
    hours: 'Mon-Fri 8am-11pm ET (Equifax), varies by bureau',
    avgWaitTime: '15-30 min',
    tipsToReachHuman: [
      'Equifax: 1-888-397-3742 — Experian: 1-888-397-3742 — TransUnion: 1-800-916-8800',
      'Press 0 to reach an agent at any bureau',
      'For a free annual credit report visit annualcreditreport.com',
      'To freeze your credit you must contact each bureau separately',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'The three major credit bureaus handle credit reports, fraud alerts, credit freezes, and dispute resolution.',
    logo: 'C',
  },

  // ─── Software (6) ────────────────────────────────────────────────────
  {
    slug: 'zoom',
    name: 'Zoom',
    category: 'software',
    phoneNumber: '1-888-799-0125',
    phoneNumberUS: '1-888-799-0125',
    phoneNumberUK: '0800-368-7314',
    chatUrl: 'https://support.zoom.us/hc/en/articles/201362003',
    supportUrl: 'https://support.zoom.us/',
    hours: '24/7',
    avgWaitTime: '5-15 min',
    tipsToReachHuman: [
      'Press 0 to skip the menu',
      'Say "representative" when prompted',
      'Use the chat on their website for quick questions',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Zoom support covers video call setup, audio issues, screen sharing, account management, and meeting scheduling.',
    logo: 'Z',
  },
  {
    slug: 'skype',
    name: 'Skype (Microsoft)',
    category: 'software',
    phoneNumber: '1-800-642-7676',
    phoneNumberUS: '1-800-642-7676',
    phoneNumberUK: '0800-026-0329',
    chatUrl: 'https://support.microsoft.com/en-us/skype',
    supportUrl: 'https://support.skype.com/',
    hours: 'Mon-Fri 6am-6pm PT',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Say "Skype" then "speak to a person"',
      'Press 0 to skip automated options',
      'Use the Microsoft support virtual agent and request a callback',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Skype support helps with video calls, audio problems, account recovery, and Skype credit/subscription issues.',
    logo: 'S',
  },
  {
    slug: 'adobe',
    name: 'Adobe',
    category: 'software',
    phoneNumber: '1-800-833-6687',
    phoneNumberUS: '1-800-833-6687',
    phoneNumberUK: '0207-365-0735',
    chatUrl: 'https://helpx.adobe.com/contact.html',
    supportUrl: 'https://helpx.adobe.com/',
    hours: 'Mon-Fri 5am-7pm PT',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 to skip the menu',
      'Say "representative" when prompted',
      'Use the live chat for subscription and billing questions',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Adobe support covers Acrobat PDF reader, Photoshop, Creative Cloud subscriptions, billing, and installation issues.',
    logo: 'A',
  },
  {
    slug: 'intuit-turbotax',
    name: 'Intuit TurboTax',
    category: 'software',
    phoneNumber: '1-800-446-8848',
    phoneNumberUS: '1-800-446-8848',
    phoneNumberUK: null,
    chatUrl: 'https://support.turbotax.intuit.com/contact/',
    supportUrl: 'https://support.turbotax.intuit.com/',
    hours: 'Mon-Sun 5am-9pm PT (extended during tax season)',
    avgWaitTime: '10-30 min',
    tipsToReachHuman: [
      'Press 0 to skip the menu',
      'Say "speak to an agent" at the prompt',
      'Call earlier in tax season for shorter waits',
      'Use the TurboTax assistant chat for quick questions',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'TurboTax support covers tax filing help, software installation, e-filing issues, refund tracking, and account management.',
    logo: 'T',
  },
  {
    slug: 'dropbox',
    name: 'Dropbox',
    category: 'software',
    phoneNumber: null,
    phoneNumberUS: null,
    phoneNumberUK: null,
    chatUrl: 'https://www.dropbox.com/support',
    supportUrl: 'https://help.dropbox.com/',
    hours: '24/7 (online support)',
    avgWaitTime: '1-2 hours (email), instant (chat for paid plans)',
    tipsToReachHuman: [
      'Dropbox does not offer phone support',
      'Paid plan users can access live chat support',
      'Email support through the Help Center for free accounts',
      'Use the community forums for common questions',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'Dropbox support covers file storage, sharing, syncing issues, account recovery, and subscription management.',
    logo: 'D',
  },
  {
    slug: 'quickbooks',
    name: 'QuickBooks (Intuit)',
    category: 'software',
    phoneNumber: '1-800-446-8848',
    phoneNumberUS: '1-800-446-8848',
    phoneNumberUK: '0808-234-5337',
    chatUrl: 'https://quickbooks.intuit.com/learn-support/contact',
    supportUrl: 'https://quickbooks.intuit.com/learn-support/',
    hours: 'Mon-Fri 6am-6pm PT, Sat 6am-3pm PT',
    avgWaitTime: '10-20 min',
    tipsToReachHuman: [
      'Press 0 to skip the automated menu',
      'Say "representative" when prompted',
      'Have your QuickBooks subscription details ready',
    ],
    seniorSupport: false,
    seniorLine: null,
    description: 'QuickBooks support covers accounting software, bookkeeping, invoicing, payroll, and financial report issues.',
    logo: 'Q',
  },
]

// ── Popular Companies (top 20 most-searched) ────────────────────────────────

export const POPULAR_COMPANIES: string[] = [
  'apple-iphone',
  'samsung',
  'amazon',
  'netflix',
  'facebook',
  'gmail-google',
  'verizon',
  'att',
  't-mobile',
  'comcast-xfinity',
  'medicare',
  'social-security',
  'bank-of-america',
  'chase',
  'microsoft-windows',
  'consumer-cellular',
  'lively-jitterbug',
  'amazon-alexa',
  'yahoo-mail',
  'best-buy',
]

// ── Utility Functions ───────────────────────────────────────────────────────

export function getAllSupport(): SupportEntry[] {
  return SUPPORT_DATABASE
}

export function getSupportBySlug(slug: string): SupportEntry | undefined {
  return SUPPORT_DATABASE.find((entry) => entry.slug === slug)
}

export function getSupportByCategory(category: SupportCategory): SupportEntry[] {
  return SUPPORT_DATABASE.filter((entry) => entry.category === category)
}

export function getCategoryBySlug(slug: string): SupportCategoryInfo | undefined {
  return SUPPORT_CATEGORIES.find((cat) => cat.slug === slug)
}
